"use client"

import React, { useState, useEffect, useRef, useCallback, useMemo } from "react"
import JSZip from "jszip"
import { Bot, ChevronLeft, ChevronRight, ChevronDown, Grid, Grid3X3, X, PanelLeftClose, PanelLeftOpen, PanelRightClose, PanelRightOpen, Plus, MessageSquarePlus, Download, FolderHeart, ArrowLeft } from "lucide-react"
import { Button } from "@/components/ui/button"
import { ScrollArea } from "@/components/ui/scroll-area"
import { ChatMessage } from "@/components/chat-message"
import { PreviewPanel } from "@/components/preview-panel"
import { StatusIndicator } from "@/components/status-indicator"
import { useChat } from "@ai-sdk/react"
import { useDarkMode, useKeyboardShortcuts, useResizing } from "@/hooks/use-ui-utils"
import { SettingsPanel } from "@/components/settings-panel"
import { AppDrawer } from "@/components/app-drawer"
import { ChatInput } from "@/components/chat-input"
import { Dock } from "@/components/dock"
import { AgentStatus, Provider, SavedApp } from "@/types"
import { saveAppToDB, getAllAppsFromDB, deleteAppFromDB, saveChatHistoryToDB, getChatHistoryFromDB, deleteChatHistoryFromDB } from "@/lib/db"

export default function Home() {
  const [status, setStatus] = useState<AgentStatus>("idle")
  const [showSettings, setShowSettings] = useState(false)
  const [showPreview, setShowPreview] = useState(false)
  const [showAppDrawer, setShowAppDrawer] = useState(false)
  const [galleryIndex, setGalleryIndex] = useState(0)
  const [providers, setProviders] = useState<Provider[]>([])
  const [selectedProvider, setSelectedProvider] = useState<string>("")
  const [loadingProviders, setLoadingProviders] = useState(true)
  const [previewWidth, setPreviewWidth] = useState(30)
  const [isResizing, setIsResizing] = useState(false)
  const activeCategoryRef = useRef("All")
  const abortControllerRef = useRef<AbortController | null>(null)
  const messagesEndRef = useRef<HTMLDivElement>(null)
  const lastAssistantMsgRef = useRef<string>("")
  const [localPreviewCode, setLocalPreviewCode] = useState("")
  const [blobUrl, setBlobUrl] = useState<string>("")
  const [savedApps, setSavedApps] = useState<SavedApp[]>([])
  const [longPressTimer, setLongPressTimer] = useState<NodeJS.Timeout | null>(null)
  const [contextMenu, setContextMenu] = useState<{ appId: string; x: number; y: number } | null>(null)
  const [longPressedApp, setLongPressedApp] = useState<SavedApp | null>(null)
  const [isBuilding, setIsBuilding] = useState(false)
  const [initialMessages, setInitialMessages] = useState<any[]>([])
  const [autoGenerated, setAutoGenerated] = useState(false)
  const [currentChatMessages, setCurrentChatMessages] = useState<any[]>([])
  const [editedAppCode, setEditedAppCode] = useState<string>("")
  const [isEditing, setIsEditing] = useState(false)
  const [shareMessage, setShareMessage] = useState("")
  const [showScrollButton, setShowScrollButton] = useState(false)
  const [previewImageUrl, setPreviewImageUrl] = useState<string | null>(null)
  const [recentChats, setRecentChats] = useState<{ id: string; title: string; timestamp: number }[]>([])
  const [settingsExpanded, setSettingsExpanded] = useState(false)
  const [currentChatId, setCurrentChatId] = useState<string>("")
  const [chatKey, setChatKey] = useState("0")
  const [messagePreviews, setMessagePreviews] = useState<Map<number, string>>(new Map())
  const [selectedLanguage, setSelectedLanguage] = useState<string>("")
  const selectedLanguageRef = useRef(selectedLanguage)
  const [messageImages, setMessageImages] = useState<Map<number, string>>(new Map())

  const languages = [
    { code: "", name: "English", native: "English" },
    { code: "hi", name: "Hindi", native: "हिंदी" },
    { code: "bn", name: "Bengali", native: "বাংলা" },
    { code: "te", name: "Telugu", native: "తెలుగు" },
    { code: "mr", name: "Marathi", native: "मराठी" },
    { code: "ta", name: "Tamil", native: "தமிழ்" },
    { code: "gu", name: "Gujarati", native: "ગુજરાતી" },
    { code: "kn", name: "Kannada", native: "ಕನ್ನಡ" },
    { code: "ml", name: "Malayalam", native: "മലയാളം" },
    { code: "pa", name: "Punjabi", native: "ਪੰਜਾਬੀ" },
    { code: "ur", name: "Urdu", native: "اردو" },
    { code: "or", name: "Odia", native: "ଓଡ଼ିଆ" },
    { code: "as", name: "Assamese", native: "অসমীয়া" },
    { code: "mai", name: "Maithili", native: "मैथिली" },
  ]
  const currentLang = languages.find(l => l.code === selectedLanguage) || languages[0]
  
  useEffect(() => {
    selectedLanguageRef.current = selectedLanguage
  }, [selectedLanguage])

  const { darkMode, setDarkMode } = useDarkMode()

  const { handleMouseDown: handleResizeMouseDown } = useResizing(setPreviewWidth, setIsResizing)
  
  useKeyboardShortcuts(
    showSettings, setShowSettings,
    showPreview, setShowPreview,
    showAppDrawer, setShowAppDrawer,
    setContextMenu, setLongPressedApp,
    savedApps, galleryIndex, setGalleryIndex
  )

  const {
    messages,
    input,
    setInput,
    setMessages,
    isLoading: isGenerating,
    append,
    stop: stopChat,
  } = useChat({
    key: chatKey,
    api: "/api/router",
    initialMessages: initialMessages,
    body: { selectedProvider, selectedLanguage },
    onError: (error) => {
      console.error("Chat error:", error)
      setStatus("error")
    },
    onFinish: () => {
      if (isBuilding) setStatus("ready")
    },
    onToolCall: (params) => {
      if (params.toolCall.toolName === "announce") {
        const { phase } = params.toolCall.args as any
        setStatus(phase as AgentStatus)
      }
    },
    experimental_throttle: 100,
  })

  // Auto scroll to bottom only when new assistant message arrives
  useEffect(() => {
    const lastMsg = messages[messages.length - 1]
    if (lastMsg && lastMsg.role === 'assistant' && lastMsg.id !== lastAssistantMsgRef.current) {
      lastAssistantMsgRef.current = lastMsg.id
      setTimeout(() => {
        messagesEndRef.current?.scrollIntoView({ behavior: "smooth" })
      }, 100)
    }
  }, [messages])

  // Persistence and loading effects
  useEffect(() => {
    const savedShowPreview = localStorage.getItem("showPreview")
    const savedShowSettings = localStorage.getItem("showSettings")
    if (savedShowPreview !== null) setShowPreview(savedShowPreview === "true")
    if (savedShowSettings !== null) setShowSettings(savedShowSettings === "true")
    
    const savedRecentChats = localStorage.getItem("recentChats")
    if (savedRecentChats) {
      try {
        setRecentChats(JSON.parse(savedRecentChats))
      } catch (e) { console.error("Failed to load recent chats") }
    }

    const savedLanguage = localStorage.getItem("selectedLanguage")
    if (savedLanguage !== null) setSelectedLanguage(savedLanguage)
  }, [])

  useEffect(() => {
    localStorage.setItem("showPreview", showPreview.toString())
  }, [showPreview])

  useEffect(() => {
    localStorage.setItem("showSettings", showSettings.toString())
  }, [showSettings])

  useEffect(() => {
    localStorage.setItem("selectedLanguage", selectedLanguage)
  }, [selectedLanguage])

  useEffect(() => {
    setHasSavedToGallery(false)
    const loadSavedApps = async () => {
      const savedAppsData = await getAllAppsFromDB()
      const appsWithUrls = savedAppsData.map(app => {
        if (app.code.startsWith('data:image/')) {
          return { ...app, url: app.code }
        }
        try {
          const blob = new Blob([app.code], { type: 'text/html' })
          return { ...app, url: URL.createObjectURL(blob) }
        } catch (e) { return app }
      })
      setSavedApps(appsWithUrls)
    }
    loadSavedApps()
  }, [])

  const regeneratePreviewsFromMessages = (msgs: any[]) => {
    const newPreviews = new Map<number, string>()
    msgs.forEach((message, i) => {
      if (message.role === 'assistant' && message.content) {
        const match = message.content.match(/```html([\s\S]*?)```/)
        if (match) {
          const htmlCode = match[1].trim()
          const htmlContent = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"><title>My App</title><style>*{margin:0;padding:0;box-sizing:border-box;}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#1a1a2e;color:#eaeaea;min-height:100vh;padding:16px;}.app-container{max-width:100%;margin:0 auto;}</style></head><body><div class="app-container">${htmlCode}</div><script>window.parent.postMessage({ type: 'loaded' }, '*');</script></body></html>`
          const blob = new Blob([htmlContent], { type: 'text/html' })
          const url = URL.createObjectURL(blob)
          newPreviews.set(i, url)
        }
      }
    })
    setMessagePreviews(newPreviews)
  }

  const extractCodeFromMessage = (msg: any): string | null => {
    if (msg.role === 'assistant' && msg.content) {
      const match = msg.content.match(/```html([\s\S]*?)```/)
      if (match) {
        return match[1].trim()
      }
    }
    return null
  }

  const handleSaveFromChat = async (msgIndex: number) => {
    const msg = messages[msgIndex]
    const code = extractCodeFromMessage(msg)
    if (!code) return

    const msgContent = msg.content || ''
    const fillerWords = ['a', 'an', 'the', 'make', 'make a', 'build', 'build a', 'create', 'create a', 'can you', 'please', 'i want', 'build me', 'create me', 'app', 'application', 'in', 'telugu', 'hindi', 'tamil', 'kannada', 'malayalam', 'bengali', 'marathi', 'gujarati']
    let rawName = msgContent.replace(/```html[\s\S]*?```/g, '').trim() || 'My App'
    fillerWords.forEach(word => {
      rawName = rawName.replace(new RegExp('\\b' + word + '\\b', 'gi'), ' ')
    })
    rawName = rawName.replace(/[^\p{L}\p{N}\s]/gu, ' ').replace(/\s+/g, ' ').trim()
    const words = rawName.split(' ').filter(w => w.trim().length > 0)
    let appName = words.slice(0, 3).join(' ').trim() || 'My App'
    appName = appName.split(' ').map((w, i) => {
      const cleaned = w.trim()
      if (!cleaned) return ''
      return i === 0 ? cleaned.charAt(0).toUpperCase() + cleaned.slice(1).toLowerCase() : cleaned.toLowerCase()
    }).join(' ').trim()
    if (appName.length > 20) {
      appName = words.slice(0, 2).join(' ').trim()
      appName = appName.charAt(0).toUpperCase() + appName.slice(1).toLowerCase()
    }
    if (!appName || appName.length < 2) {
      appName = 'My App'
    }

    const existingApp = savedApps.find(app => app.code === code)
    if (existingApp) return

    const newApp: SavedApp = {
      id: Date.now().toString(),
      name: appName,
      icon: getAppIcon(appName),
      code: code,
      url: "",
      chatMessages: messages,
      createdAt: Date.now()
    }
    await saveAppToDB(newApp)
    const blob = new Blob([code], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const appWithUrl = { ...newApp, url }
    setSavedApps(prev => [appWithUrl, ...prev])
  }

  const handleDownloadFromChat = (msgIndex: number) => {
    const msg = messages[msgIndex]
    const code = extractCodeFromMessage(msg)
    if (!code) return

    const zip = new JSZip()
    const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title>My App</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #1a1a2e; color: #eaeaea; min-height: 100vh; padding: 16px; }
    .app-container { max-width: 100%; margin: 0 auto; }
  </style>
</head>
<body>
  <div class="app-container">
    ${code}
  </div>
</body>
</html>`
    zip.file("index.html", htmlContent)
    zip.generateAsync({ type: "blob" }).then((content) => {
      const url = URL.createObjectURL(content)
      const link = document.createElement('a')
      link.href = url
      link.download = `app-${Date.now()}.zip`
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      URL.revokeObjectURL(url)
    })
  }

  const handleImageSaveFromChat = async (msgIndex: number) => {
    const msg = messages[msgIndex]
    const imageUrl = messageImages.get(msgIndex) || (msg as any).imageUrl
    if (!imageUrl) return

    const msgContent = msg.content || ''
    const promptMatch = msgContent.match(/IMAGE_REQUEST:\s*(.+)/i)
    const rawPrompt = promptMatch ? promptMatch[1].trim() : 'Image'
    const fillerWords = ['a', 'an', 'the', 'generate', 'show', 'me', 'picture', 'photo', 'image', 'of', 'create', 'make']
    let rawName = rawPrompt
    fillerWords.forEach(word => {
      rawName = rawName.replace(new RegExp('\\b' + word + '\\b', 'gi'), ' ')
    })
    rawName = rawName.replace(/[^\p{L}\p{N}\s]/gu, ' ').replace(/\s+/g, ' ').trim()
    const words = rawName.split(' ').filter(w => w.trim().length > 0)
    let appName = words.slice(0, 3).join(' ').trim() || 'Image'
    appName = appName.split(' ').map((w, i) => {
      const cleaned = w.trim()
      if (!cleaned) return ''
      return i === 0 ? cleaned.charAt(0).toUpperCase() + cleaned.slice(1).toLowerCase() : cleaned.toLowerCase()
    }).join(' ').trim()
    if (appName.length > 20) {
      appName = words.slice(0, 2).join(' ').trim()
      appName = appName.charAt(0).toUpperCase() + appName.slice(1).toLowerCase()
    }
    if (!appName || appName.length < 2) {
      appName = 'Image'
    }

    const existingApp = savedApps.find(app => app.url === imageUrl)
    if (existingApp) return

    try {
      const response = await fetch(imageUrl)
      const blob = await response.blob()
      const reader = new FileReader()
      reader.onloadend = async () => {
        const base64 = reader.result as string
        const newApp: SavedApp = {
          id: Date.now().toString(),
          name: appName,
          icon: "🖼️",
          code: base64,
          url: imageUrl,
          createdAt: Date.now()
        }
        await saveAppToDB(newApp)
        setSavedApps(prev => [newApp, ...prev])
      }
      reader.readAsDataURL(blob)
    } catch (error) {
      console.error("Failed to save image:", error)
    }
  }

  const handleImageDownloadFromChat = async (msgIndex: number) => {
    const msg = messages[msgIndex]
    const imageUrl = messageImages.get(msgIndex) || (msg as any).imageUrl
    if (!imageUrl) return

    const msgContent = msg.content || ''
    const promptMatch = msgContent.match(/IMAGE_REQUEST:\s*(.+)/i)
    const rawPrompt = promptMatch ? promptMatch[1].trim() : 'image'
    const fillerWords = ['a', 'an', 'the', 'generate', 'show', 'me', 'picture', 'photo', 'image', 'of', 'create', 'make']
    let rawName = rawPrompt
    fillerWords.forEach(word => {
      rawName = rawName.replace(new RegExp('\\b' + word + '\\b', 'gi'), ' ')
    })
    rawName = rawName.replace(/[^\p{L}\p{N}\s]/gu, ' ').replace(/\s+/g, ' ').trim()
    const words = rawName.split(' ').filter(w => w.trim().length > 0)
    let fileName = words.slice(0, 4).join('-').trim() || 'image'
    fileName = fileName.replace(/[^a-zA-Z0-9-]/g, '-').toLowerCase()
    if (!fileName) fileName = 'image'

    const extension = imageUrl.includes('image/png') ? 'png' : 'jpg'
    const link = document.createElement('a')
    link.href = imageUrl
    link.download = `${fileName}-${Date.now()}.${extension}`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  }

  const handleImageOpenFromChat = (msgIndex: number) => {
    const imageUrl = messageImages.get(msgIndex) || (messages[msgIndex] as any).imageUrl
    if (!imageUrl) return
    setPreviewImageUrl(imageUrl)
    setShowPreview(true)
  }

  const isAppSavedInChat = (msgIndex: number): boolean => {
    const msg = messages[msgIndex]
    const code = extractCodeFromMessage(msg)
    if (!code) return false
    return savedApps.some(app => app.code === code)
  }

  const isImageSavedInChat = (msgIndex: number): boolean => {
    const imageUrl = messageImages.get(msgIndex)
    if (!imageUrl) return false
    return savedApps.some(app => app.url === imageUrl || app.code === imageUrl)
  }

  useEffect(() => {
    if (currentChatMessages.length > 0) {
      setInitialMessages(currentChatMessages)
      setInput("")
      regeneratePreviewsFromMessages(currentChatMessages)
    } else {
      const savedMessagesData = localStorage.getItem("chatMessages")
      if (savedMessagesData) {
        try {
          const messagesData = JSON.parse(savedMessagesData)
          if (messagesData.length > 0) {
            setInitialMessages(messagesData)
            setInput("")
            regeneratePreviewsFromMessages(messagesData)
          }
        } catch (e) { console.error("Failed to load chat messages") }
      }
    }
  }, [currentChatMessages])

  useEffect(() => {
    savedApps.forEach(app => {
      const appWithoutUrl = { ...app, url: "" }
      saveAppToDB(appWithoutUrl)
    })
  }, [savedApps])

useEffect(() => {
    if (messages.length > 0) {
      const recentMessages = messages.slice(-20)

      const userMessages = recentMessages.filter(m => m.role === 'user')
      if (userMessages.length > 0) {
        const lastUserMsg = userMessages[userMessages.length - 1]
        const title = lastUserMsg.content?.substring(0, 40).replace(/[^a-zA-Z0-9 ]/g, ' ').trim() || 'New Chat'

        const chatId = currentChatId || Date.now().toString()
        if (!currentChatId) {
          setCurrentChatId(chatId)
        }

        saveChatHistoryToDB(chatId, recentMessages).catch(() => {})

        setRecentChats(prev => {
          const existingIndex = prev.findIndex(c => c.id === chatId)
          let updated
          if (existingIndex >= 0) {
            updated = prev.map((c, i) => i === existingIndex ? { ...c, title, timestamp: Date.now() } : c)
          } else {
            const filtered = prev.filter(c => c.title !== title)
            const newChat = { id: chatId, title, timestamp: Date.now() }
            updated = [newChat, ...filtered].slice(0, 10)
          }
          try {
            localStorage.setItem("recentChats", JSON.stringify(updated))
          } catch (e) {
            // Ignore if recentChats fails
          }
          return updated
        })
      }
    }
  }, [messages, currentChatId])

  useEffect(() => {
    const urlParams = new URLSearchParams(window.location.search)
    const encodedApp = urlParams.get('app')
    if (encodedApp) {
      try {
        const decoded = JSON.parse(atob(encodedApp))
        const sharedApp: SavedApp = {
          id: Date.now().toString(),
          name: decoded.name || 'Shared App',
          icon: decoded.icon || '📱',
          code: decoded.code,
          url: '',
          chatMessages: decoded.chatMessages,
          createdAt: decoded.createdAt || Date.now()
        }
        setInitialMessages(decoded.chatMessages || [])
        setCurrentChatMessages(decoded.chatMessages || [])
        setLocalPreviewCode(decoded.code)
        setEditedAppCode(decoded.code)
        setShowPreview(true)
        setShowAppDrawer(false)
        setBlobUrl("")
        setTimeout(() => {
          const htmlContent = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"><title>${sharedApp.name}</title><style>*{margin:0;padding:0;box-sizing:border-box;}html,body{height:100%;width:100%;overflow:hidden;display:flex;justify-content:center;align-items:center;}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#1a1a2e;color:#eaeaea;width:100vw;height:100vh;}.app-container{width:100%;height:100%;}</style></head><body><div class="app-container">${decoded.code}</div><script>window.parent.postMessage({ type: 'loaded' }, '*');</script></body></html>`
          const blob = new Blob([htmlContent], { type: 'text/html' })
          setBlobUrl(URL.createObjectURL(blob))
        }, 0)
        window.history.replaceState({}, '', window.location.pathname)
      } catch (error) {
        console.error("Failed to load shared app:", error)
      }
    }
  }, [])

  useEffect(() => {
    if (shareMessage) {
      const timer = setTimeout(() => setShareMessage(""), 3000)
      return () => clearTimeout(timer)
    }
  }, [shareMessage])

  useEffect(() => {
    return () => {
      savedApps.forEach(app => { if (app.url) URL.revokeObjectURL(app.url) })
    }
  }, [savedApps])

  useEffect(() => {
    const newImages = new Map<number, string>()
    messages.forEach((msg, i) => {
      if (msg.role === 'assistant' && msg.content) {
        const imageMatch = msg.content.match(/@image\[([^\]]+)\]/)
        if (imageMatch) {
          newImages.set(i, imageMatch[1])
        }
      }
      if (msg.role === 'assistant' && (msg as any).imageUrl) {
        newImages.set(i, (msg as any).imageUrl)
      }
    })
    if (newImages.size > 0) {
      setMessageImages(prev => {
        const updated = new Map(prev)
        newImages.forEach((url, idx) => updated.set(idx, url))
        return updated
      })
    }
  }, [messages])

  useEffect(() => {
    async function loadProviders() {
      try {
        const res = await fetch("/api/router")
        const data = await res.json()
        const textProviders = data.text_generation || []
        setProviders(textProviders)
        const routerProvider = textProviders.find((p: Provider) => p.router === true)
        if (routerProvider) setSelectedProvider(routerProvider.name)
      } catch (error) {
        console.error("Failed to load providers:", error)
      } finally {
        setLoadingProviders(false)
      }
    }
    loadProviders()
  }, [])

  const handleConsoleMessage = (msg: string) => {
    window.dispatchEvent(new CustomEvent("addErrorToFixer", { detail: msg }))
  }

  const stopGeneration = () => {
    if (abortControllerRef.current) abortControllerRef.current.abort()
    abortControllerRef.current = null
    stopChat()
  }

  const handleSubmit = async (e?: React.FormEvent, language?: string) => {
    if (e) e.preventDefault()
    if (!input.trim() || isGenerating) return

    const userContent = input.toLowerCase()
    const imageKeywords = ["image", "picture", "photo", "draw", "generate image", "create image", "make picture"]
    const audioKeywords = ["audio", "sound", "speech", "voice", "tts", "music", "song"]
    const isImageRequest = imageKeywords.some(kw => userContent.includes(kw))
    const isAudioRequest = audioKeywords.some(kw => userContent.includes(kw))

    // Handle image requests directly (bypass useChat which expects streaming)
    if (isImageRequest) {
      setStatus("generating_image")
      const userMsg = {
        id: Date.now().toString(),
        role: "user" as const,
        content: input,
      }
      setMessages(prev => [...prev, userMsg])
      setInput("")
      
      try {
        const response = await fetch("/api/image", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ prompt: input }),
        })
        const data = await response.json()
        if (data.imageUrl) {
          const imageMsg = {
            id: Date.now().toString(),
            role: "assistant" as const,
            content: "",
            imageUrl: data.imageUrl,
          }
          setMessages(prev => [...prev, imageMsg])
        } else {
          const errorMsg = {
            id: Date.now().toString(),
            role: "assistant" as const,
            content: "Sorry, I couldn't generate the image. Please try again.",
          }
          setMessages(prev => [...prev, errorMsg])
        }
      } catch (error) {
        console.error("Image generation error:", error)
      }
      setStatus("idle")
      return
    }

    // Handle audio requests directly
    if (isAudioRequest) {
      setStatus("coding")
      try {
        const response = await fetch("/api/audio", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ prompt: input }),
        })
        const data = await response.json()
        if (data.audioUrl) {
          const audioMsg = {
            id: Date.now().toString(),
            role: "assistant" as const,
            content: "Here's the audio you requested:",
            audioUrl: data.audioUrl,
          }
          const userMsg = {
            id: (Date.now() - 1).toString(),
            role: "user" as const,
            content: input,
          }
          setMessages(prev => [...prev, userMsg, audioMsg])
        } else {
          const errorMsg = {
            id: Date.now().toString(),
            role: "assistant" as const,
            content: "Sorry, I couldn't generate the audio. Please try again.",
          }
          const userMsg = {
            id: (Date.now() - 1).toString(),
            role: "user" as const,
            content: input,
          }
          setMessages(prev => [...prev, userMsg, errorMsg])
        }
      } catch (error) {
        console.error("Audio generation error:", error)
      }
      setStatus("idle")
      setInput("")
      return
    }

    if (abortControllerRef.current) abortControllerRef.current.abort()
    abortControllerRef.current = null
    setLocalPreviewCode("")
    setBlobUrl("")
    setStatus("idle")
    setIsBuilding(true)
    setHasSavedToGallery(false)
    setSessionApps([])
    setCurrentAppIndex(-1)
    setAutoGenerated(false)
    
    const currentLang = language || selectedLanguageRef.current
    await append({ role: "user", content: input })
    setInput("")
  }

  function getAppIcon(appName: string): string {
    const lowered = appName.toLowerCase()
    if (lowered.includes('sudoku') || lowered.includes('puzzle')) return '🧩'
    if (lowered.includes('todo') || lowered.includes('task')) return '✅'
    if (lowered.includes('calc')) return '🔢'
    if (lowered.includes('note')) return '📝'
    if (lowered.includes('clock')) return '⏰'
    if (lowered.includes('weather')) return '🌤️'
    if (lowered.includes('game')) return '🎮'
    if (lowered.includes('photo') || lowered.includes('image')) return '📷'
    if (lowered.includes('music')) return '🎵'
    if (lowered.includes('contact')) return '📱'
    if (lowered.includes('shop') || lowered.includes('cart')) return '🛒'
    if (lowered.includes('food')) return '🍳'
    if (lowered.includes('chat')) return '💬'
    if (lowered.includes('fitness')) return '💪'
    if (lowered.includes('travel')) return '✈️'
    if (lowered.includes('book')) return '📚'
    if (lowered.includes('video')) return '🎬'
    if (lowered.includes('camera')) return '📸'
    if (lowered.includes('map')) return '🗺️'
    if (lowered.includes('bank') || lowered.includes('money')) return '💰'
    if (lowered.includes('art')) return '🎨'
    return '📱'
  }

  useEffect(() => {
    let htmlCode = ""
    for (let i = messages.length - 1; i >= 0; i--) {
      const message = messages[i]
      if (message.role === 'assistant' && message.content) {
        const match = message.content.match(/```html([\s\S]*?)```/)
        if (match) {
          htmlCode = match[1].trim()
          break
        }
      }
    }
    if (htmlCode) setLocalPreviewCode(htmlCode)
  }, [messages])

useEffect(() => {
    if (status === "ready" && localPreviewCode && autoGenerated) {
      const lastUserMsg = messages.filter(m => m.role === 'user').pop()
      const rawName = lastUserMsg?.content?.substring(0, 30).replace(/[^a-zA-Z0-9 ]/g, ' ').trim() || 'My App'
      const appName = rawName.split(' ').slice(0, 2).join(' ')
      const newApp: SavedApp = {
        id: Date.now().toString() + Math.random().toString(36).substr(2, 9),
        name: appName,
        icon: getAppIcon(appName),
        code: localPreviewCode,
        url: "",
        createdAt: Date.now()
      }
      setSessionApps(prev => [...prev.filter(a => a.code !== localPreviewCode), newApp])
      setCurrentAppIndex(prev => prev + 1)
      setIsBuilding(false)
    }
  }, [status, localPreviewCode, messages])

  useEffect(() => {
    let htmlCode = ""
    for (let i = messages.length - 1; i >= 0; i--) {
      const message = messages[i]
      if (message.role === 'assistant' && message.content) {
        const match = message.content.match(/```html([\s\S]*?)```/)
        if (match) {
          htmlCode = match[1].trim()
          break
        }
      }
    }
    if (htmlCode && !autoGenerated) {
      const isSessionApp = sessionApps.some(app => app.code === htmlCode)
      if (!isSessionApp) {
        setLocalPreviewCode(htmlCode)
        setAutoGenerated(true)
      }
    }
  }, [messages])

  useEffect(() => {
    if (localPreviewCode) {
      if (blobUrl) URL.revokeObjectURL(blobUrl)
      const htmlContent = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"><title>My App</title><style>*{margin:0;padding:0;box-sizing:border-box;}html,body{height:100%;width:100%;overflow:hidden;display:flex;justify-content:center;align-items:center;}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#1a1a2e;color:#eaeaea;width:100vw;height:100vh;}.app-container{width:100%;height:100%;}</style></head><body><div class="app-container">${localPreviewCode}</div><script>window.parent.postMessage({ type: 'loaded' }, '*');</script></body></html>`
      const blob = new Blob([htmlContent], { type: 'text/html' })
      const url = URL.createObjectURL(blob)
      setBlobUrl(url)
      
      // Find the assistant message that contains this code and store preview with it
      for (let i = messages.length - 1; i >= 0; i--) {
        const message = messages[i]
        if (message.role === 'assistant' && message.content) {
          const match = message.content.match(/```html([\s\S]*?)```/)
          if (match && match[1].trim() === localPreviewCode) {
            setMessagePreviews(prev => new Map(prev).set(i, url))
            break
          }
        }
      }
      
      return () => URL.revokeObjectURL(url)
    }
  }, [localPreviewCode])


  const openSavedApp = (app: SavedApp) => {
    setLocalPreviewCode(app.code)
    setShowPreview(true)
    setShowAppDrawer(false)
    setBlobUrl("")
    setInput("")
    setTimeout(() => {
      const htmlContent = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"><title>${app.name}</title><style>*{margin:0;padding:0;box-sizing:border-box;}html,body{height:100%;width:100%;overflow:hidden;display:flex;justify-content:center;align-items:center;}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#1a1a2e;color:#eaeaea;width:100vw;height:100vh;}.app-container{width:100%;height:100%;}</style></head><body><div class="app-container">${app.code}</div><script>window.parent.postMessage({ type: 'loaded' }, '*');</script></body></html>`
      const blob = new Blob([htmlContent], { type: 'text/html' })
      setBlobUrl(URL.createObjectURL(blob))
    }, 0)
  }

  const handleEditApp = async (app: SavedApp) => {
    setIsEditing(false)
    setLocalPreviewCode(app.code)
    setEditedAppCode(app.code)
    setShowPreview(true)
    setShowAppDrawer(false)
    setBlobUrl("")
    setHasSavedToGallery(false)
    setTimeout(() => {
      const htmlContent = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"><title>Edit: ${app.name}</title><style>*{margin:0;padding:0;box-sizing:border-box;}html,body{height:100%;width:100%;overflow:hidden;display:flex;justify-content:center;align-items:center;}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#1a1a2e;color:#eaeaea;width:100vw;height:100vh;}.app-container{width:100%;height:100%;}</style></head><body><div class="app-container">${app.code}</div><script>window.parent.postMessage({ type: 'loaded' }, '*');</script></body></html>`
      const blob = new Blob([htmlContent], { type: 'text/html' })
      setBlobUrl(URL.createObjectURL(blob))
    }, 0)
  }

  const handleSaveEditedApp = async () => {
    const updatedApp: SavedApp = {
      ...savedApps.find(app => app.code === editedAppCode)!,
      code: editedAppCode,
      chatMessages: messages,
      createdAt: Date.now()
    }
    await saveAppToDB(updatedApp)
    setSavedApps(prev => prev.map(app => app.id === updatedApp.id ? updatedApp : app))
    setIsEditing(false)
    setEditedAppCode("")
  }

  const removeApp = async (appId: string) => {
    await deleteAppFromDB(appId)
    setSavedApps(prev => prev.filter(a => a.id !== appId))
    setContextMenu(null)
    setLongPressedApp(null)
  }

  const handleLongPressStart = (app: SavedApp, e: any) => {
    if (e?.preventDefault) e.preventDefault()
    setLongPressedApp(app)
    setContextMenu(null)
    const timer = setTimeout(() => {
      const target = e?.target || document.activeElement
      const rect = (target as HTMLElement).getBoundingClientRect()
      setContextMenu({
        appId: app.id,
        x: rect.left,
        y: rect.bottom + 5
      })
    }, 500)
    setLongPressTimer(timer)
  }

  const handleLongPressEnd = () => {
    if (longPressTimer) clearTimeout(longPressTimer)
    setLongPressTimer(null)
    setContextMenu(null)
    setLongPressedApp(null)
  }

  const newSession = () => {
    const newChatId = Date.now().toString()
    setChatKey(prev => String(Number(prev) + 1))
    setCurrentChatId(newChatId)
    setCurrentChatMessages([])
    setInput("")
    setInitialMessages([])
    setStatus("idle")
    setIsBuilding(false)
    setLocalPreviewCode("")
    setEditedAppCode("")
    setIsEditing(false)
    setHasSavedToGallery(false)
    setSessionApps([])
    setCurrentAppIndex(-1)
    setMessagePreviews(new Map())
    setMessageImages(new Map())
    if (blobUrl) { URL.revokeObjectURL(blobUrl); setBlobUrl("") }
    localStorage.removeItem("chatMessages")
  }

const [hasSavedToGallery, setHasSavedToGallery] = useState(false)
  const [sessionApps, setSessionApps] = useState<SavedApp[]>([])
  const [currentAppIndex, setCurrentAppIndex] = useState(-1)
  const [activeChatTab, setActiveChatTab] = useState<string | null>(null)
  const [visibleRange, setVisibleRange] = useState({ start: 0, end: 50 })

  useEffect(() => {
    if (sessionApps.length > 0) {
      setHasSavedToGallery(false)
    }
  }, [sessionApps, currentAppIndex])

  useEffect(() => {
    if (!showPreview) {
      setHasSavedToGallery(false)
    }
  }, [showPreview])

  const handleSaveToGallery = async () => {
    try {
      const codeToSave = localPreviewCode || (sessionApps[currentAppIndex]?.code ?? '')
      if (!codeToSave) {
        return
      }
      const lastUserMsg = messages.filter(m => m.role === 'user').pop()
      const fillerWords = ['a', 'an', 'the', 'make', 'make a', 'build', 'build a', 'create', 'create a', 'can you', 'please', 'i want', 'build me', 'create me', 'app', 'application', 'in', 'telugu', 'hindi', 'tamil', 'kannada', 'malayalam', 'bengali', 'marathi', 'gujarati']
      let rawName = lastUserMsg?.content || 'My App'
      fillerWords.forEach(word => {
        rawName = rawName.replace(new RegExp('\\b' + word + '\\b', 'gi'), ' ')
      })
      rawName = rawName.replace(/[^\p{L}\p{N}\s]/gu, ' ').replace(/\s+/g, ' ').trim()
      const words = rawName.split(' ').filter(w => w.trim().length > 0)
      let appName = words.slice(0, 3).join(' ').trim() || 'My App'
      appName = appName.split(' ').map((w, i) => {
        const cleaned = w.trim()
        if (!cleaned) return ''
        return i === 0 ? cleaned.charAt(0).toUpperCase() + cleaned.slice(1).toLowerCase() : cleaned.toLowerCase()
      }).join(' ').trim()
      if (appName.length > 20) {
        appName = words.slice(0, 2).join(' ').trim()
        appName = appName.charAt(0).toUpperCase() + appName.slice(1).toLowerCase()
      }
      if (!appName || appName.length < 2) {
        appName = 'My App'
      }
      const existingApp = savedApps.find(app => app.code === codeToSave)
      if (existingApp) {
        return
      }
      const newApp: SavedApp = {
        id: Date.now().toString(),
        name: appName,
        icon: getAppIcon(appName),
        code: codeToSave,
        url: "",
        chatMessages: messages,
        createdAt: Date.now()
      }
      await saveAppToDB(newApp)
      const blob = new Blob([codeToSave], { type: 'text/html' })
      const url = URL.createObjectURL(blob)
      const appWithUrl = { ...newApp, url }
      setSavedApps(prev => [appWithUrl, ...prev])
      setHasSavedToGallery(true)
    } catch (error) {
      console.error('Failed to save to gallery:', error)
    }
  }

  useEffect(() => {
    if (sessionApps.length > 0) {
      setHasSavedToGallery(false)
    }
  }, [sessionApps, currentAppIndex])

  useEffect(() => {
    if (!showPreview) {
      setHasSavedToGallery(false)
    }
  }, [showPreview])

  useEffect(() => {
    const totalMessages = messages.length
    if (totalMessages > 50) {
      setVisibleRange({ start: totalMessages - 50, end: totalMessages })
    } else {
      setVisibleRange({ start: 0, end: totalMessages })
    }
  }, [messages.length])

  const handleSwitchToSavedApp = (app: SavedApp) => {
    setIsEditing(false)
    setLocalPreviewCode(app.code)
    setEditedAppCode(app.code)
    setShowAppDrawer(false)
    setActiveChatTab(app.id)
    setBlobUrl("")
    setInput("")
    
    const isBase64Image = app.code.startsWith('data:image/')
    
    if (isBase64Image) {
      setPreviewImageUrl(app.code)
      setShowPreview(true)
    } else {
      setPreviewImageUrl(null)
      setShowPreview(true)
      setTimeout(() => {
        const htmlContent = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"><title>${app.name}</title><style>*{margin:0;padding:0;box-sizing:border-box;}html,body{height:100%;width:100%;overflow:hidden;display:flex;justify-content:center;align-items:center;}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#1a1a2e;color:#eaeaea;width:100vw;height:100vh;}.app-container{width:100%;height:100%;}</style></head><body><div class="app-container">${app.code}</div><script>window.parent.postMessage({ type: 'loaded' }, '*');</script></body></html>`
        const blob = new Blob([htmlContent], { type: 'text/html' })
        setBlobUrl(URL.createObjectURL(blob))
      }, 0)
    }
  }

  const handleShareApp = async (app: SavedApp) => {
    try {
      const shareData = {
        code: app.code,
        chatMessages: app.chatMessages,
        name: app.name,
        icon: app.icon,
        createdAt: app.createdAt
      }
      const encoded = btoa(JSON.stringify(shareData))
      const shareUrl = `${window.location.origin}${window.location.pathname}?app=${encoded}`
      setShareMessage(`Link copied to clipboard!`)
      await navigator.clipboard.writeText(shareUrl)
      setTimeout(() => setShareMessage(""), 3000)
    } catch (error) {
      console.error("Failed to share:", error)
      setShareMessage("Failed to copy link")
      setTimeout(() => setShareMessage(""), 3000)
    }
  }

  const handleDeleteApp = (appId: string) => {
    setSavedApps(prev => prev.filter(app => app.id !== appId))
  }

  const handleDownloadApp = (app: SavedApp) => {
    if (app.code.startsWith('data:image/') || app.code.startsWith('data:video/') || app.code.startsWith('data:audio/')) {
      const link = document.createElement('a')
      link.href = app.code
      link.download = `${app.name}.${app.code.split(';')[0].split('/')[1] || 'bin'}`
      link.click()
    }
  }

  const handleRunApp = (app: SavedApp) => {
    if (!app.code.startsWith('data:')) {
      setShowPreview(true)
      setPreviewImageUrl(null)
      setBlobUrl("")
      setTimeout(() => {
        const htmlContent = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"><title>${app.name}</title><style>*{margin:0;padding:0;box-sizing:border-box;}html,body{height:100%;width:100%;overflow:hidden;display:flex;justify-content:center;align-items:center;}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#1a1a2e;color:#eaeaea;width:100vw;height:100vh;}.app-container{width:100%;height:100%;}</style></head><body><div class="app-container">${app.code}</div><script>window.parent.postMessage({ type: 'loaded' }, '*');</script></body></html>`
        const blob = new Blob([htmlContent], { type: 'text/html' })
        setBlobUrl(URL.createObjectURL(blob))
      }, 0)
    }
  }

  const handleNewChat = () => {
    newSession()
    setActiveChatTab(null)
  }

  const loadRecentChat = (chatId: string) => {
    const chat = recentChats.find(c => c.id === chatId)
    if (chat) {
      setCurrentChatId(chatId)
      getChatHistoryFromDB(chatId).then((savedMessagesData) => {
        if (savedMessagesData && savedMessagesData.length > 0) {
          setInitialMessages(savedMessagesData)
          setCurrentChatMessages(savedMessagesData)
        }
      })
    }
  }

  const deleteChat = (chatId: string) => {
    setRecentChats(prev => {
      const updated = prev.filter(c => c.id !== chatId)
      localStorage.setItem("recentChats", JSON.stringify(updated))
      return updated
    })
    deleteChatHistoryFromDB(chatId)
    if (currentChatId === chatId) {
      setCurrentChatMessages([])
      setInput("")
      setInitialMessages([])
      setLocalPreviewCode("")
      setMessagePreviews(new Map())
    }
  }

  useEffect(() => {
    console.log('Session apps updated:', sessionApps.length, 'Current index:', currentAppIndex)
    if (sessionApps.length > 0) {
      setHasSavedToGallery(false)
    }
  }, [sessionApps, currentAppIndex])

  const navigateToNextApp = () => {

    if (currentAppIndex < sessionApps.length - 1) {
      const nextApp = sessionApps[currentAppIndex + 1]
      if (nextApp) {
        setLocalPreviewCode(nextApp.code)
        setCurrentAppIndex(prev => prev + 1)
        setBlobUrl("")
        setTimeout(() => {
          const htmlContent = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"><title>${nextApp.name}</title><style>*{margin:0;padding:0;box-sizing:border-box;}html,body{height:100%;width:100%;overflow:hidden;display:flex;justify-content:center;align-items:center;}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#1a1a2e;color:#eaeaea;width:100vw;height:100vh;}.app-container{width:100%;height:100%;}</style></head><body><div class="app-container">${nextApp.code}</div><script>window.parent.postMessage({ type: 'loaded' }, '*');</script></body></html>`
          const blob = new Blob([htmlContent], { type: 'text/html' })
          setBlobUrl(URL.createObjectURL(blob))
        }, 0)
      }
    }
  }

  const navigateToPrevApp = () => {
    if (currentAppIndex > 0) {
      const prevApp = sessionApps[currentAppIndex - 1]
      if (prevApp) {
        setLocalPreviewCode(prevApp.code)
        setCurrentAppIndex(prev => prev - 1)
        setBlobUrl("")
        setTimeout(() => {
          const htmlContent = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"><title>${prevApp.name}</title><style>*{margin:0;padding:0;box-sizing:border-box;}html,body{height:100%;width:100%;overflow:hidden;display:flex;justify-content:center;align-items:center;}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#1a1a2e;color:#eaeaea;width:100vw;height:100vh;}.app-container{width:100%;height:100%;}</style></head><body><div class="app-container">${prevApp.code}</div><script>window.parent.postMessage({ type: 'loaded' }, '*');</script></body></html>`
          const blob = new Blob([htmlContent], { type: 'text/html' })
          setBlobUrl(URL.createObjectURL(blob))
        }, 0)
      }
    }
  }

  return (
    <div className="flex h-screen bg-[#121215]">
      {shareMessage && (
        <div className="fixed top-4 left-1/2 transform -translate-x-1/2 bg-muted text-foreground px-4 py-2 rounded-lg shadow-md z-50">
          {shareMessage}
        </div>
      )}
      
      <SettingsPanel
        showSettings={showSettings}
        setShowSettings={setShowSettings}
        recentChats={recentChats}
        onLoadChat={loadRecentChat}
        onDeleteChat={deleteChat}
      />

      {showPreview && window.innerWidth < 768 && (
        <div className="fixed inset-0 z-50 bg-[#121215]">
          <div className="flex items-center justify-between px-4 py-3">
            <span className="text-sm font-medium">{savedApps.find(app => app.code === editedAppCode)?.name || "Current Chat"}</span>
            <div className="flex gap-1">
              <Button variant="ghost" size="icon" className="h-6 w-6" onClick={() => { setShowAppDrawer(true); setShowPreview(false); }}>
                <ArrowLeft className="h-4 w-4" />
              </Button>
              <Button variant="ghost" size="icon" className="h-6 w-6" onClick={() => setShowPreview(false)}>
                <X className="h-4 w-4" />
              </Button>
            </div>
          </div>
          <div className="h-[calc(100vh-53px)]">
            {blobUrl ? (
              <PreviewPanel previewUrl={blobUrl} onConsoleMessage={handleConsoleMessage} stopAutoReload={status === "ready"} />
            ) : (
              <div className="h-full flex items-center justify-center text-muted-foreground"><p className="text-sm">Preview will appear here</p></div>
            )}
          </div>
        </div>
      )}

      <div className={`flex-1 flex min-w-0 transition-all duration-300 ${showAppDrawer ? 'w-full md:w-[50%]' : 'w-full md:w-[50%]'}`}>
        <div className={`absolute top-4 left-4 z-50 ${showAppDrawer ? 'hidden md:block' : ''}`}>
          {!showSettings && (
            <button 
              onClick={() => setShowSettings(true)}
              className="p-2 text-[#666666] hover:text-[#888888] transition-colors"
            >
              <PanelLeftOpen className="h-5 w-5" />
            </button>
          )}
        </div>

        <div className={`flex-1 flex min-h-0 ${showAppDrawer ? 'hidden md:flex' : ''}`}>
          <div className="flex-1 flex flex-col min-w-0">
            <ScrollArea className="flex-1 bg-[#121215] [&::-webkit-scrollbar]:hidden">
              <div className="px-4 py-2 space-y-4">
                {useMemo(() => {
                  const visibleMessages = messages.slice(visibleRange.start, visibleRange.end)
                  return visibleMessages.map((msg, idx) => {
                    const actualIdx = visibleRange.start + idx
                    const msgPreviewUrl = messagePreviews.get(actualIdx)
                    const msgImageUrl = messageImages.get(actualIdx) || (msg as any).imageUrl
                    const isLatestAssistant = msg.role === 'assistant' && actualIdx === messages.length - 1
                    const hasCode = extractCodeFromMessage(msg) !== null
                    const msgWithImage = { ...msg, imageUrl: msgImageUrl }
                    return (
                      <div key={msg.id} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'} gap-2`}>
                        <div className={`max-w-[90%] ${msg.role === 'user' ? 'items-end' : 'items-start'}`}>
                          <ChatMessage 
                            message={msgWithImage} 
                            previewUrl={msgPreviewUrl} 
                            onPreviewClick={() => setShowPreview(true)} 
                            onSaveToGallery={hasCode ? () => handleSaveFromChat(actualIdx) : undefined}
                            onDownload={hasCode ? () => handleDownloadFromChat(actualIdx) : undefined}
                            hasSavedToGallery={hasCode && isAppSavedInChat(actualIdx)}
                            status={isLatestAssistant ? status : undefined}
                            onImageSave={msgImageUrl ? () => handleImageSaveFromChat(actualIdx) : undefined}
                            onImageDownload={msgImageUrl ? () => handleImageDownloadFromChat(actualIdx) : undefined}
                            onImageOpen={msgImageUrl ? () => handleImageOpenFromChat(actualIdx) : undefined}
                            hasImageSavedToGallery={msgImageUrl && isImageSavedInChat(actualIdx)}
                          />
                        </div>
                      </div>
                    )
                  })
                }, [messages, visibleRange.start, visibleRange.end, messagePreviews, messageImages, status, savedApps])}
                <div ref={messagesEndRef} />
              </div>
            </ScrollArea>

            <div className="px-4 pb-4">
              <Dock
                onNewChat={newSession}
                onToggleGallery={() => setShowAppDrawer(!showAppDrawer)}
                selectedLanguage={selectedLanguage}
                onLanguageChange={(lang) => {
                  setSelectedLanguage(lang)
                }}
              />
              <div className="mt-2">
                <ChatInput 
                  input={input} setInput={setInput} isGenerating={isGenerating}
                  handleSubmit={handleSubmit} stopGeneration={stopGeneration}
                />
              </div>
            </div>
          </div>
        </div>
      </div>

      <AppDrawer 
        showAppDrawer={showAppDrawer} setShowAppDrawer={setShowAppDrawer}
        savedApps={savedApps} openSavedApp={openSavedApp} removeApp={removeApp}
        editApp={handleEditApp} shareApp={handleShareApp} runApp={handleRunApp}
        deleteApp={handleDeleteApp} downloadApp={handleDownloadApp}
        handleSwitchToSavedApp={handleSwitchToSavedApp}
        setLongPressedApp={setLongPressedApp}
        contextMenu={contextMenu} longPressedApp={longPressedApp}
        selectedIndex={galleryIndex} setSelectedIndex={setGalleryIndex}
      />

      <div className={`transition-all duration-300 overflow-hidden ${showPreview ? "w-full sm:w-[50%]" : "w-0"}`}>
        {showPreview && (
          <>
            <div className="flex-1 h-full overflow-hidden [&::-webkit-scrollbar]:w-2 [&::-webkit-scrollbar-thumb]:bg-[#404040] [&::-webkit-scrollbar-track]:bg-transparent">
              {previewImageUrl ? (
                <PreviewPanel 
                  imageUrl={previewImageUrl} 
                  appName={sessionApps[currentAppIndex]?.name || "Image Preview"} 
                  onConsoleMessage={handleConsoleMessage} 
                  stopAutoReload={status === "ready"} 
                  onBack={() => { setShowAppDrawer(true); setShowPreview(false); setPreviewImageUrl(null) }}
                  onClose={() => { setShowPreview(false); setPreviewImageUrl(null) }}
                />
              ) : blobUrl ? (
                <PreviewPanel previewUrl={blobUrl} appName={sessionApps[currentAppIndex]?.name || "My App"} onConsoleMessage={handleConsoleMessage} stopAutoReload={status === "ready"} onBack={() => { setShowAppDrawer(true); setShowPreview(false) }} onClose={() => setShowPreview(false)} />
              ) : (
                <div className="h-full flex items-center justify-center text-muted-foreground"><p className="text-sm">Preview will appear here</p></div>
              )}
            </div>
            <div className="cursor-col-resize hover:bg-primary/20 transition-colors" style={{ width: '4px' }} onMouseDown={handleResizeMouseDown} />
          </>
        )}
      </div>
    </div>
  )
}
