"use client"

import React, { useState, useEffect, useRef, useCallback } from "react"
import { Bot, ChevronLeft, ChevronRight, Grid, X, PanelLeftClose, PanelLeftOpen, PanelRightClose, PanelRightOpen } from "lucide-react"
import { Button } from "@/components/ui/button"
import { ScrollArea } from "@/components/ui/scroll-area"
import { ChatMessage } from "@/components/chat-message"
import { PreviewPanel } from "@/components/preview-panel"
import { StatusIndicator } from "@/components/status-indicator"
import { useChat } from "@ai-sdk/react"
import { useDarkMode, useKeyboardShortcuts, useResizing } from "@/hooks/use-ui-utils"
import { SettingsPanel } from "@/components/settings-panel"
import { AppDrawer } from "@/components/app-drawer"
import { ChatInput } from "@/components/chat-input"
import { AgentStatus, Provider, SavedApp } from "@/types"
import { saveAppToDB, getAllAppsFromDB, deleteAppFromDB } from "@/lib/db"

export default function Home() {
  const [status, setStatus] = useState<AgentStatus>("idle")
  const [showSettings, setShowSettings] = useState(false)
  const [showPreview, setShowPreview] = useState(false)
  const [showAppDrawer, setShowAppDrawer] = useState(false)
  const [providers, setProviders] = useState<Provider[]>([])
  const [selectedProvider, setSelectedProvider] = useState<string>("")
  const [loadingProviders, setLoadingProviders] = useState(true)
  const [previewWidth, setPreviewWidth] = useState(30)
  const [isResizing, setIsResizing] = useState(false)
  const abortControllerRef = useRef<AbortController | null>(null)
  const messagesEndRef = useRef<HTMLDivElement>(null)
  const [localPreviewCode, setLocalPreviewCode] = useState("")
  const [blobUrl, setBlobUrl] = useState<string>("")
  const [savedApps, setSavedApps] = useState<SavedApp[]>([])
  const [longPressTimer, setLongPressTimer] = useState<NodeJS.Timeout | null>(null)
  const [contextMenu, setContextMenu] = useState<{ appId: string; x: number; y: number } | null>(null)
  const [longPressedApp, setLongPressedApp] = useState<SavedApp | null>(null)
  const [isBuilding, setIsBuilding] = useState(false)
  const [initialMessages, setInitialMessages] = useState<any[]>([])
  const [autoGenerated, setAutoGenerated] = useState(false)
  const [currentChatMessages, setCurrentChatMessages] = useState<any[]>([])
  const [editedAppCode, setEditedAppCode] = useState<string>("")
  const [isEditing, setIsEditing] = useState(false)
  const [shareMessage, setShareMessage] = useState("")
  const [showScrollButton, setShowScrollButton] = useState(false)
  const [recentChats, setRecentChats] = useState<{ id: string; title: string; timestamp: number }[]>([])
  const [settingsExpanded, setSettingsExpanded] = useState(false)

  const { darkMode, setDarkMode } = useDarkMode()

  const { handleMouseDown: handleResizeMouseDown } = useResizing(setPreviewWidth, setIsResizing)
  
  useKeyboardShortcuts(
    showSettings, setShowSettings,
    showPreview, setShowPreview,
    showAppDrawer, setShowAppDrawer,
    setContextMenu, setLongPressedApp
  )

  const {
    messages,
    input,
    setInput,
    isLoading: isGenerating,
    append,
    stop: stopChat,
  } = useChat({
    api: "/api/chat",
    initialMessages: initialMessages,
    body: { isAutonomous: true, selectedProvider },
    onError: (error) => {
      console.error("Chat error:", error)
      setStatus("error")
    },
    onFinish: () => {
      if (isBuilding) setStatus("ready")
    },
    onToolCall: (params) => {
      if (params.toolCall.toolName === "announce") {
        const { phase } = params.toolCall.args as any
        setStatus(phase as AgentStatus)
      }
    },
    experimental_throttle: 100,
  })

  // Persistence and loading effects
  useEffect(() => {
    const savedShowPreview = localStorage.getItem("showPreview")
    const savedShowSettings = localStorage.getItem("showSettings")
    if (savedShowPreview !== null) setShowPreview(savedShowPreview === "true")
    if (savedShowSettings !== null) setShowSettings(savedShowSettings === "true")
    
    const savedRecentChats = localStorage.getItem("recentChats")
    if (savedRecentChats) {
      try {
        setRecentChats(JSON.parse(savedRecentChats))
      } catch (e) { console.error("Failed to load recent chats") }
    }
  }, [])

  useEffect(() => {
    localStorage.setItem("showPreview", showPreview.toString())
  }, [showPreview])

  useEffect(() => {
    localStorage.setItem("showSettings", showSettings.toString())
  }, [showSettings])

  useEffect(() => {
    setHasSavedToGallery(false)
    const loadSavedApps = async () => {
      const savedAppsData = await getAllAppsFromDB()
      const appsWithUrls = savedAppsData.map(app => {
        try {
          const blob = new Blob([app.code], { type: 'text/html' })
          return { ...app, url: URL.createObjectURL(blob) }
        } catch (e) { return app }
      })
      setSavedApps(appsWithUrls)
    }
    loadSavedApps()
  }, [])

  useEffect(() => {
    if (currentChatMessages.length > 0) {
      setInitialMessages(currentChatMessages)
      setInput("")
      for (let i = currentChatMessages.length - 1; i >= 0; i--) {
        const message = currentChatMessages[i]
        if (message.role === 'assistant' && message.content) {
          const match = message.content.match(/```html([\s\S]*?)```/)
          if (match) {
            setLocalPreviewCode(match[1].trim())
            break
          }
        }
      }
    } else {
      const savedMessagesData = localStorage.getItem("chatMessages")
      if (savedMessagesData) {
        try {
          const messagesData = JSON.parse(savedMessagesData)
          if (messagesData.length > 0) {
            setInitialMessages(messagesData)
            setInput("")
            for (let i = messagesData.length - 1; i >= 0; i--) {
              const message = messagesData[i]
              if (message.role === 'assistant' && message.content) {
                const match = message.content.match(/```html([\s\S]*?)```/)
                if (match) {
                  setLocalPreviewCode(match[1].trim())
                  break
                }
              }
            }
          }
        } catch (e) { console.error("Failed to load chat messages") }
      }
    }
  }, [currentChatMessages])

  useEffect(() => {
    savedApps.forEach(app => {
      const appWithoutUrl = { ...app, url: "" }
      saveAppToDB(appWithoutUrl)
    })
  }, [savedApps])

  useEffect(() => {
    if (messages.length > 0) {
      localStorage.setItem("chatMessages", JSON.stringify(messages))
      
      const userMessages = messages.filter(m => m.role === 'user')
      if (userMessages.length > 0) {
        const lastUserMsg = userMessages[userMessages.length - 1]
        const title = lastUserMsg.content?.substring(0, 40).replace(/[^a-zA-Z0-9 ]/g, ' ').trim() || 'New Chat'
        const chatId = Date.now().toString()
        
        setRecentChats(prev => {
          const filtered = prev.filter(c => c.title !== title)
          const newChat = { id: chatId, title, timestamp: Date.now() }
          const updated = [newChat, ...filtered].slice(0, 10)
          localStorage.setItem("recentChats", JSON.stringify(updated))
          return updated
        })
      }
    }
  }, [messages])

  useEffect(() => {
    const urlParams = new URLSearchParams(window.location.search)
    const encodedApp = urlParams.get('app')
    if (encodedApp) {
      try {
        const decoded = JSON.parse(atob(encodedApp))
        const sharedApp: SavedApp = {
          id: Date.now().toString(),
          name: decoded.name || 'Shared App',
          icon: decoded.icon || '📱',
          code: decoded.code,
          url: '',
          chatMessages: decoded.chatMessages,
          createdAt: decoded.createdAt || Date.now()
        }
        setInitialMessages(decoded.chatMessages || [])
        setCurrentChatMessages(decoded.chatMessages || [])
        setLocalPreviewCode(decoded.code)
        setEditedAppCode(decoded.code)
        setShowPreview(true)
        setShowAppDrawer(false)
        setBlobUrl("")
        setTimeout(() => {
          const htmlContent = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"><title>${sharedApp.name}</title><style>*{margin:0;padding:0;box-sizing:border-box;}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#1a1a2e;color:#eaeaea;min-height:100vh;padding:16px;}.app-container{max-width:100%;margin:0 auto;}</style></head><body><div class="app-container">${decoded.code}</div><script>window.parent.postMessage({ type: 'loaded' }, '*');</script></body></html>`
          const blob = new Blob([htmlContent], { type: 'text/html' })
          setBlobUrl(URL.createObjectURL(blob))
        }, 0)
        window.history.replaceState({}, '', window.location.pathname)
      } catch (error) {
        console.error("Failed to load shared app:", error)
      }
    }
  }, [])

  useEffect(() => {
    if (shareMessage) {
      const timer = setTimeout(() => setShareMessage(""), 3000)
      return () => clearTimeout(timer)
    }
  }, [shareMessage])

  useEffect(() => {
    return () => {
      savedApps.forEach(app => { if (app.url) URL.revokeObjectURL(app.url) })
    }
  }, [savedApps])

  useEffect(() => {
    async function loadProviders() {
      try {
        const res = await fetch("/api/chat")
        const data = await res.json()
        setProviders(data.providers)
        const defaultProvider = data.defaultProvider || data.providers.find((p: Provider) => p.default)
        if (defaultProvider) setSelectedProvider(defaultProvider.name)
      } catch (error) {
        console.error("Failed to load providers:", error)
      } finally {
        setLoadingProviders(false)
      }
    }
    loadProviders()
  }, [])

  const handleConsoleMessage = (msg: string) => {
    window.dispatchEvent(new CustomEvent("addErrorToFixer", { detail: msg }))
  }

  const stopGeneration = () => {
    if (abortControllerRef.current) abortControllerRef.current.abort()
    abortControllerRef.current = null
    stopChat()
  }

  const handleSubmit = async (e?: React.FormEvent) => {
    if (e) e.preventDefault()
    if (!input.trim() || isGenerating) return
    if (abortControllerRef.current) abortControllerRef.current.abort()
    abortControllerRef.current = null
    setLocalPreviewCode("")
    setBlobUrl("")
    setStatus("idle")
    setIsBuilding(true)
    setHasSavedToGallery(false)
    setSessionApps([])
    setCurrentAppIndex(-1)
    setAutoGenerated(false)
    await append({ role: "user", content: input })
    setInput("")
  }

  function getAppIcon(appName: string): string {
    const lowered = appName.toLowerCase()
    if (lowered.includes('sudoku') || lowered.includes('puzzle')) return '🧩'
    if (lowered.includes('todo') || lowered.includes('task')) return '✅'
    if (lowered.includes('calc')) return '🔢'
    if (lowered.includes('note')) return '📝'
    if (lowered.includes('clock')) return '⏰'
    if (lowered.includes('weather')) return '🌤️'
    if (lowered.includes('game')) return '🎮'
    if (lowered.includes('photo') || lowered.includes('image')) return '📷'
    if (lowered.includes('music')) return '🎵'
    if (lowered.includes('contact')) return '📱'
    if (lowered.includes('shop') || lowered.includes('cart')) return '🛒'
    if (lowered.includes('food')) return '🍳'
    if (lowered.includes('chat')) return '💬'
    if (lowered.includes('fitness')) return '💪'
    if (lowered.includes('travel')) return '✈️'
    if (lowered.includes('book')) return '📚'
    if (lowered.includes('video')) return '🎬'
    if (lowered.includes('camera')) return '📸'
    if (lowered.includes('map')) return '🗺️'
    if (lowered.includes('bank') || lowered.includes('money')) return '💰'
    if (lowered.includes('art')) return '🎨'
    return '📱'
  }

  useEffect(() => {
    let htmlCode = ""
    for (let i = messages.length - 1; i >= 0; i--) {
      const message = messages[i]
      if (message.role === 'assistant' && message.content) {
        const match = message.content.match(/```html([\s\S]*?)```/)
        if (match) {
          htmlCode = match[1].trim()
          break
        }
      }
    }
    if (htmlCode) setLocalPreviewCode(htmlCode)
  }, [messages])

useEffect(() => {
    if (status === "ready" && localPreviewCode && autoGenerated) {
      const lastUserMsg = messages.filter(m => m.role === 'user').pop()
      const rawName = lastUserMsg?.content?.substring(0, 30).replace(/[^a-zA-Z0-9 ]/g, ' ').trim() || 'My App'
      const appName = rawName.split(' ').slice(0, 2).join(' ')
      const newApp: SavedApp = {
        id: Date.now().toString() + Math.random().toString(36).substr(2, 9),
        name: appName,
        icon: getAppIcon(appName),
        code: localPreviewCode,
        url: "",
        createdAt: Date.now()
      }
      setSessionApps(prev => [...prev.filter(a => a.code !== localPreviewCode), newApp])
      setCurrentAppIndex(prev => prev + 1)
      setIsBuilding(false)
    }
  }, [status, localPreviewCode, messages])

  useEffect(() => {
    let htmlCode = ""
    for (let i = messages.length - 1; i >= 0; i--) {
      const message = messages[i]
      if (message.role === 'assistant' && message.content) {
        const match = message.content.match(/```html([\s\S]*?)```/)
        if (match) {
          htmlCode = match[1].trim()
          break
        }
      }
    }
    if (htmlCode && !autoGenerated) {
      const isSessionApp = sessionApps.some(app => app.code === htmlCode)
      if (!isSessionApp) {
        setLocalPreviewCode(htmlCode)
        setAutoGenerated(true)
      }
    }
  }, [messages])

  useEffect(() => {
    if (localPreviewCode) {
      if (blobUrl) URL.revokeObjectURL(blobUrl)
      const htmlContent = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"><title>My App</title><style>*{margin:0;padding:0;box-sizing:border-box;}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#1a1a2e;color:#eaeaea;min-height:100vh;padding:16px;}.app-container{max-width:100%;margin:0 auto;}</style></head><body><div class="app-container">${localPreviewCode}</div><script>window.parent.postMessage({ type: 'loaded' }, '*');</script></body></html>`
      const blob = new Blob([htmlContent], { type: 'text/html' })
      const url = URL.createObjectURL(blob)
      setBlobUrl(url)
      return () => URL.revokeObjectURL(url)
    }
  }, [localPreviewCode])


  const openSavedApp = (app: SavedApp) => {
    setLocalPreviewCode(app.code)
    setShowPreview(true)
    setShowAppDrawer(false)
    setBlobUrl("")
    setTimeout(() => {
      const htmlContent = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"><title>${app.name}</title><style>*{margin:0;padding:0;box-sizing:border-box;}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#1a1a2e;color:#eaeaea;min-height:100vh;padding:16px;}.app-container{max-width:100%;margin:0 auto;}</style></head><body><div class="app-container">${app.code}</div><script>window.parent.postMessage({ type: 'loaded' }, '*');</script></body></html>`
      const blob = new Blob([htmlContent], { type: 'text/html' })
      setBlobUrl(URL.createObjectURL(blob))
    }, 0)
  }

  const handleEditApp = async (app: SavedApp) => {
    setIsEditing(false)
    setInitialMessages(app.chatMessages || [])
    setCurrentChatMessages(app.chatMessages || [])
    setLocalPreviewCode(app.code)
    setEditedAppCode(app.code)
    setShowPreview(true)
    setShowAppDrawer(false)
    setBlobUrl("")
    setHasSavedToGallery(false)
    setTimeout(() => {
      const htmlContent = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"><title>Edit: ${app.name}</title><style>*{margin:0;padding:0;box-sizing:border-box;}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#1a1a2e;color:#eaeaea;min-height:100vh;padding:16px;}.app-container{max-width:100%;margin:0 auto;}</style></head><body><div class="app-container">${app.code}</div><script>window.parent.postMessage({ type: 'loaded' }, '*');</script></body></html>`
      const blob = new Blob([htmlContent], { type: 'text/html' })
      setBlobUrl(URL.createObjectURL(blob))
    }, 0)
  }

  const handleSaveEditedApp = async () => {
    const updatedApp: SavedApp = {
      ...savedApps.find(app => app.code === editedAppCode)!,
      code: editedAppCode,
      chatMessages: messages,
      createdAt: Date.now()
    }
    await saveAppToDB(updatedApp)
    setSavedApps(prev => prev.map(app => app.id === updatedApp.id ? updatedApp : app))
    setIsEditing(false)
    setEditedAppCode("")
  }

  const removeApp = async (appId: string) => {
    await deleteAppFromDB(appId)
    setSavedApps(prev => prev.filter(a => a.id !== appId))
    setContextMenu(null)
    setLongPressedApp(null)
  }

  const handleLongPressStart = (app: SavedApp, e: any) => {
    if (e?.preventDefault) e.preventDefault()
    setLongPressedApp(app)
    setContextMenu(null)
    const timer = setTimeout(() => {
      const target = e?.target || document.activeElement
      const rect = (target as HTMLElement).getBoundingClientRect()
      setContextMenu({
        appId: app.id,
        x: rect.left,
        y: rect.bottom + 5
      })
    }, 500)
    setLongPressTimer(timer)
  }

  const handleLongPressEnd = () => {
    if (longPressTimer) clearTimeout(longPressTimer)
    setLongPressTimer(null)
    setContextMenu(null)
    setLongPressedApp(null)
  }

const newSession = () => {
    localStorage.removeItem("chatMessages")
    setCurrentChatMessages([])
    setInput("")
    setInitialMessages([])
    setStatus("idle")
    setIsBuilding(false)
    setLocalPreviewCode("")
    setEditedAppCode("")
    setIsEditing(false)
    setHasSavedToGallery(false)
    if (blobUrl) { URL.revokeObjectURL(blobUrl); setBlobUrl("") }
  }

const [hasSavedToGallery, setHasSavedToGallery] = useState(false)
  const [sessionApps, setSessionApps] = useState<SavedApp[]>([])
  const [currentAppIndex, setCurrentAppIndex] = useState(-1)
  const [activeChatTab, setActiveChatTab] = useState<string | null>(null)

  useEffect(() => {
    if (sessionApps.length > 0) {
      setHasSavedToGallery(false)
    }
  }, [sessionApps, currentAppIndex])

  useEffect(() => {
    if (!showPreview) {
      setHasSavedToGallery(false)
    }
  }, [showPreview])

  const handleSaveToGallery = async () => {
    if (isEditing) {
      return
    }
    if (sessionApps.length > 0) {
      return
    }
    const lastUserMsg = messages.filter(m => m.role === 'user').pop()
    const rawName = lastUserMsg?.content?.substring(0, 30).replace(/[^a-zA-Z0-9 ]/g, ' ').trim() || 'My App'
    const appName = rawName.split(' ').slice(0, 2).join(' ')
    const existingApp = savedApps.find(app => app.code === localPreviewCode)
    if (existingApp) {
      return
    }
    const newApp: SavedApp = {
      id: Date.now().toString(),
      name: appName,
      icon: getAppIcon(appName),
      code: localPreviewCode,
      url: "",
      chatMessages: messages,
      createdAt: Date.now()
    }
    await saveAppToDB(newApp)
    const blob = new Blob([localPreviewCode], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const appWithUrl = { ...newApp, url }
    setSavedApps(prev => [appWithUrl, ...prev])
    setHasSavedToGallery(true)
  }

  useEffect(() => {
    if (sessionApps.length > 0) {
      setHasSavedToGallery(false)
    }
  }, [sessionApps, currentAppIndex])

  useEffect(() => {
    if (!showPreview) {
      setHasSavedToGallery(false)
    }
  }, [showPreview])

  const handleSwitchToSavedApp = (app: SavedApp) => {
    setIsEditing(false)
    setInitialMessages(app.chatMessages || [])
    setCurrentChatMessages(app.chatMessages || [])
    setLocalPreviewCode(app.code)
    setEditedAppCode(app.code)
    setShowPreview(true)
    setShowAppDrawer(false)
    setBlobUrl("")
    setActiveChatTab(app.id)
    setTimeout(() => {
      const htmlContent = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"><title>${app.name}</title><style>*{margin:0;padding:0;box-sizing:border-box;}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#1a1a2e;color:#eaeaea;min-height:100vh;padding:16px;}.app-container{max-width:100%;margin:0 auto;}</style></head><body><div class="app-container">${app.code}</div><script>window.parent.postMessage({ type: 'loaded' }, '*');</script></body></html>`
      const blob = new Blob([htmlContent], { type: 'text/html' })
      setBlobUrl(URL.createObjectURL(blob))
    }, 0)
  }

  const handleShareApp = async (app: SavedApp) => {
    try {
      const shareData = {
        code: app.code,
        chatMessages: app.chatMessages,
        name: app.name,
        icon: app.icon,
        createdAt: app.createdAt
      }
      const encoded = btoa(JSON.stringify(shareData))
      const shareUrl = `${window.location.origin}${window.location.pathname}?app=${encoded}`
      setShareMessage(`Link copied to clipboard!`)
      await navigator.clipboard.writeText(shareUrl)
      setTimeout(() => setShareMessage(""), 3000)
    } catch (error) {
      console.error("Failed to share:", error)
      setShareMessage("Failed to copy link")
      setTimeout(() => setShareMessage(""), 3000)
    }
  }

  const handleNewChat = () => {
    setActiveChatTab(null)
    setInitialMessages([])
    setLocalPreviewCode("")
    setBlobUrl("")
    setIsEditing(false)
  }

  const loadRecentChat = (chatId: string) => {
    const chat = recentChats.find(c => c.id === chatId)
    if (chat) {
      const savedMessagesData = localStorage.getItem("chatMessages")
      if (savedMessagesData) {
        try {
          const messagesData = JSON.parse(savedMessagesData)
          setInitialMessages(messagesData)
          setCurrentChatMessages(messagesData)
        } catch (e) { console.error("Failed to load chat messages") }
      }
    }
  }

  useEffect(() => {
    console.log('Session apps updated:', sessionApps.length, 'Current index:', currentAppIndex)
    if (sessionApps.length > 0) {
      setHasSavedToGallery(false)
    }
  }, [sessionApps, currentAppIndex])

  const navigateToNextApp = () => {

    if (currentAppIndex < sessionApps.length - 1) {
      const nextApp = sessionApps[currentAppIndex + 1]
      if (nextApp) {
        setLocalPreviewCode(nextApp.code)
        setCurrentAppIndex(prev => prev + 1)
        setBlobUrl("")
        setTimeout(() => {
          const htmlContent = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"><title>${nextApp.name}</title><style>*{margin:0;padding:0;box-sizing:border-box;}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#1a1a2e;color:#eaeaea;min-height:100vh;padding:16px;}.app-container{max-width:100%;margin:0 auto;}</style></head><body><div class="app-container">${nextApp.code}</div><script>window.parent.postMessage({ type: 'loaded' }, '*');</script></body></html>`
          const blob = new Blob([htmlContent], { type: 'text/html' })
          setBlobUrl(URL.createObjectURL(blob))
        }, 0)
      }
    }
  }

  const navigateToPrevApp = () => {
    if (currentAppIndex > 0) {
      const prevApp = sessionApps[currentAppIndex - 1]
      if (prevApp) {
        setLocalPreviewCode(prevApp.code)
        setCurrentAppIndex(prev => prev - 1)
        setBlobUrl("")
        setTimeout(() => {
          const htmlContent = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"><title>${prevApp.name}</title><style>*{margin:0;padding:0;box-sizing:border-box;}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#1a1a2e;color:#eaeaea;min-height:100vh;padding:16px;}.app-container{max-width:100%;margin:0 auto;}</style></head><body><div class="app-container">${prevApp.code}</div><script>window.parent.postMessage({ type: 'loaded' }, '*');</script></body></html>`
          const blob = new Blob([htmlContent], { type: 'text/html' })
          setBlobUrl(URL.createObjectURL(blob))
        }, 0)
      }
    }
  }

  return (
    <div className="flex h-screen bg-[#121215]">
      {shareMessage && (
        <div className="fixed top-4 left-1/2 transform -translate-x-1/2 bg-muted text-foreground px-4 py-2 rounded-lg shadow-md z-50">
          {shareMessage}
        </div>
      )}
      
      <SettingsPanel
        showSettings={showSettings}
        setShowSettings={setShowSettings}
        recentChats={recentChats}
        onLoadChat={loadRecentChat}
      />

      {showPreview && window.innerWidth < 768 && (
        <div className="fixed inset-0 z-50 bg-[#121215]">
          <div className="flex items-center justify-between px-4 py-3">
            <span className="text-sm font-medium">{savedApps.find(app => app.code === editedAppCode)?.name || "Current Chat"}</span>
            <Button variant="ghost" size="icon" className="h-6 w-6" onClick={() => setShowPreview(false)}>
              <X className="h-4 w-4" />
            </Button>
          </div>
          <div className="h-[calc(100vh-53px)]">
            {blobUrl ? (
              <PreviewPanel previewUrl={blobUrl} onConsoleMessage={handleConsoleMessage} stopAutoReload={status === "ready"} onSaveToGallery={handleSaveToGallery} hasSavedToGallery={hasSavedToGallery} />
            ) : (
              <div className="h-full flex items-center justify-center text-muted-foreground"><p className="text-sm">Preview will appear here</p></div>
            )}
          </div>
        </div>
      )}

      <div className="flex-1 flex flex-col min-w-0">
        <header className="px-4 py-3 flex items-center justify-between bg-[#121215] flex-shrink-0 border-b border-[#2e2e32]">
          <div className="flex items-center gap-2">
            {showSettings ? (
              <button 
                onClick={() => setShowSettings(false)}
                className="p-2 rounded-lg transition-colors bg-[#2e2e32] text-[#888888] hover:bg-[#2e2e32]/80"
              >
                <PanelLeftClose className="h-4 w-4" />
              </button>
            ) : (
              <button 
                onClick={() => setShowSettings(true)}
                className="p-2 rounded-lg transition-colors bg-[#2e2e32] text-[#888888] hover:bg-[#2e2e32]/80"
              >
                <PanelLeftOpen className="h-4 w-4" />
              </button>
            )}
            <h1 className="font-medium text-base text-[#e5e5e5]">Srishti <span className="text-red-600">AI</span></h1>
            
          </div>
          <div className="flex items-center gap-2">
            <Button variant="ghost" size="icon" className="h-6 w-6 text-[#888888]" onClick={() => setShowAppDrawer(!showAppDrawer)}>
              <Grid className="h-4 w-4" />
            </Button>
            {showPreview ? (
              <button 
                onClick={() => setShowPreview(false)}
                className="p-2 rounded-lg transition-colors bg-[#2e2e32] text-[#888888] hover:bg-[#2e2e32]/80"
                title="Collapse Preview (Ctrl+X)"
              >
                <PanelRightClose className="h-4 w-4" />
              </button>
            ) : (
              <button 
                onClick={() => setShowPreview(true)}
                className="p-2 rounded-lg transition-colors bg-[#2e2e32] text-[#888888] hover:bg-[#2e2e32]/80"
                title="Expand Preview (Ctrl+X)"
              >
                <PanelRightOpen className="h-4 w-4" />
              </button>
            )}
          </div>
        </header>

        {/* Main Content Area */}
        <div className="flex-1 flex min-h-0">
          {/* Chat Area */}
          <div className="flex-1 flex flex-col min-w-0">
            <ScrollArea className="flex-1 p-4 bg-[#121215]" style={{ scrollbarColor: '#404040 #000000', scrollbarWidth: 'thin' }}>
              <div className="max-w-2xl mx-auto space-y-4">
                {messages.map((msg, idx) => {
                  const isLastAssistant = msg.role === 'assistant' && idx === messages.findLastIndex(m => m.role === 'assistant')
                  return (
                    <div key={msg.id} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'} gap-2`}>
                      <div className="max-w-[80%] sm:max-w-[70%]"><ChatMessage message={msg} previewUrl={isLastAssistant ? blobUrl : undefined} onPreviewClick={() => setShowPreview(true)} status={status} /></div>
                    </div>
                  )
                })}
                <div ref={messagesEndRef} />
              </div>
            </ScrollArea>


            <ChatInput 
              input={input} setInput={setInput} isGenerating={isGenerating}
              handleSubmit={handleSubmit} stopGeneration={stopGeneration}
              onNewChat={newSession}
            />
          </div>
        </div>
      </div>

      <AppDrawer 
        showAppDrawer={showAppDrawer} setShowAppDrawer={setShowAppDrawer}
        savedApps={savedApps} openSavedApp={openSavedApp} removeApp={removeApp}
        editApp={handleEditApp} shareApp={handleShareApp}
        handleLongPressStart={handleLongPressStart} handleLongPressEnd={handleLongPressEnd}
        handleSwitchToSavedApp={handleSwitchToSavedApp} setContextMenu={setContextMenu}
        setLongPressedApp={setLongPressedApp} setLongPressTimer={setLongPressTimer}
        contextMenu={contextMenu} longPressedApp={longPressedApp}
      />

      <div className={`transition-all duration-300 overflow-hidden ${showPreview ? "w-full sm:w-[50%]" : "w-0"}`}>
        {showPreview && (
          <>
            <div className="flex-1 h-full overflow-hidden" style={{ scrollbarColor: '#404040 #000000', scrollbarWidth: 'thin' }}>
              {blobUrl ?               <PreviewPanel previewUrl={blobUrl} onConsoleMessage={handleConsoleMessage} stopAutoReload={status === "ready"} onSaveToGallery={handleSaveToGallery} hasSavedToGallery={hasSavedToGallery} /> : <div className="h-full flex items-center justify-center text-muted-foreground"><p className="text-sm">Preview will appear here</p></div>}
            </div>
            <div className="cursor-col-resize hover:bg-primary/20 transition-colors" style={{ width: '4px' }} onMouseDown={handleResizeMouseDown} />
          </>
        )}
      </div>
    </div>
  )
}
