"use client"

import React, { useState, useEffect, useRef, useCallback, useMemo, RefObject } from "react"
import JSZip from "jszip"
import { Bot, ChevronLeft, ChevronRight, ChevronDown, Grid, Grid3X3, X, ChevronLeft as ChevronLeftIcon, PanelRightClose, PanelRightOpen, Plus, Download, FolderHeart, ArrowLeft } from "lucide-react"
import { Button } from "@/components/ui/button"
import { ScrollArea } from "@/components/ui/scroll-area"
import { ChatMessage } from "@/components/chat-message"
import { PreviewPanel } from "@/components/preview-panel"
import { StatusIndicator } from "@/components/status-indicator"
import { useChat } from "@ai-sdk/react"
import { useDarkMode, useKeyboardShortcuts, useResizing } from "@/hooks/use-ui-utils"
import { SettingsPanel } from "@/components/settings-panel"
import { AppDrawer } from "@/components/app-drawer"
import { ChatInput } from "@/components/chat-input"
import { AgentStatus, Provider, SavedApp } from "@/types"
import { saveAppToDB, getAllAppsFromDB, deleteAppFromDB, saveChatHistoryToDB, getChatHistoryFromDB, deleteChatHistoryFromDB, clearAllChatsFromDB } from "@/lib/db"
import { wrapHtml, createBlobUrl, generateAppName, generateFileName, extractHtmlCode, findLatestHtmlCode } from "@/lib/html-wrapper"
import { detectImageIntent, detectAudioIntent, detectAppIntent, detectWeatherIntent, detectCricketIntent, detectNewsIntent, detectIntent, detectMultiIntent, type IntentResult, type MultiIntentResult } from "@/lib/intent-detector"
import { CricketCard, type CricketMatchData } from "@/components/cricket-card"
import { NewsCard, type NewsCardData } from "@/components/news-card"

export default function Home() {
  // Performance monitoring for tests
  useEffect(() => {
    if (typeof window !== 'undefined' && (window as any).__performanceMetrics) {
      return
    }
    const mem = (performance as any).memory
    ;(window as any).__performanceMetrics = {
      heapBefore: mem ? mem.usedJSHeapSize / 1024 / 1024 : 0,
      heapAfter: 0,
      startTime: Date.now(),
      messages: 0,
      blobUrls: 0,
    }
    window.addEventListener('beforeunload', () => {
      const m = (performance as any).memory
      if (m) {
        ;(window as any).__performanceMetrics.heapAfter = m.usedJSHeapSize / 1024 / 1024
      }
    })
  }, [])
  const [status, setStatus] = useState<AgentStatus>("idle")
  const [isSending, setIsSending] = useState(false)
  const [isImageGenerating, setIsImageGenerating] = useState(false)
  const [showSettings, setShowSettings] = useState(false)
  const [showPreview, setShowPreview] = useState(false)
  const [showAppDrawer, setShowAppDrawer] = useState(false)
  const [galleryIndex, setGalleryIndex] = useState(0)
  const [providers, setProviders] = useState<Provider[]>([])
  const [selectedProvider, setSelectedProvider] = useState<string>("")
  const [loadingProviders, setLoadingProviders] = useState(true)
  const [previewWidth, setPreviewWidth] = useState(30)
  const [isResizing, setIsResizing] = useState(false)
  const activeCategoryRef = useRef("All")
  const abortControllerRef = useRef<AbortController | null>(null)
  const isSendingRef = useRef(false)

  // Abort controller for cancelling streaming requests
  useEffect(() => {
    return () => {
      if (abortControllerRef.current) {
        abortControllerRef.current.abort()
        abortControllerRef.current = null
      }
    }
  }, [])
  const messagesEndRef = useRef<HTMLDivElement>(null)
  const lastAssistantMsgRef = useRef<string>("")
  const isAtBottomRef = useRef(true)
  const autoScrollRef = useRef(true)

  const scrollToBottom = useCallback(() => {
    const viewport = document.querySelector('[data-radix-scroll-area-viewport]') as HTMLElement | null
    if (viewport) {
      viewport.scrollTo({ top: viewport.scrollHeight, behavior: "smooth" })
    }
  }, [])
  const [localPreviewCode, setLocalPreviewCode] = useState("")
  const [blobUrl, setBlobUrl] = useState<string>("")
  const [savedApps, setSavedApps] = useState<SavedApp[]>([])
  const [longPressTimer, setLongPressTimer] = useState<NodeJS.Timeout | null>(null)
  const [contextMenu, setContextMenu] = useState<{ appId: string; x: number; y: number } | null>(null)
  const [longPressedApp, setLongPressedApp] = useState<SavedApp | null>(null)
  const [isBuilding, setIsBuilding] = useState(false)
  const [initialMessages, setInitialMessages] = useState<any[]>([])
  const [autoGenerated, setAutoGenerated] = useState(false)
  const [currentChatMessages, setCurrentChatMessages] = useState<any[]>([])
  const [editedAppCode, setEditedAppCode] = useState<string>("")
  const [isEditing, setIsEditing] = useState(false)
  const [shareMessage, setShareMessage] = useState("")
  const [showScrollButton, setShowScrollButton] = useState(false)
  const [previewImageUrl, setPreviewImageUrl] = useState<string | null>(null)
  const [recentChats, setRecentChats] = useState<{ id: string; title: string; timestamp: number }[]>([])
  const [settingsExpanded, setSettingsExpanded] = useState(false)
  const [currentChatId, setCurrentChatId] = useState<string>("")
  const [chatKey, setChatKey] = useState("0")
  const [messagePreviews, setMessagePreviews] = useState<Map<number, string>>(new Map())
  const previewCacheRef = useRef<Map<number, string>>(new Map())
  const [selectedLanguage, setSelectedLanguage] = useState<string>("")
  const selectedLanguageRef = useRef(selectedLanguage)
  const [messageImages, setMessageImages] = useState<Map<number, string>>(new Map())
  const messageImagesRef = useRef(messageImages)
  useEffect(() => { messageImagesRef.current = messageImages }, [messageImages])
  const [mediaNavIndex, setMediaNavIndex] = useState(0)
  const mediaAppsRef = useRef<SavedApp[]>([])
  const [hasSavedToGallery, setHasSavedToGallery] = useState(false)
  const [purpose, setPurpose] = useState<string>("general")
  const purposeRef = useRef(purpose)
  useEffect(() => { purposeRef.current = purpose }, [purpose])

  const setPurposeImmediate = (p: string) => {
    setPurpose(p)
    purposeRef.current = p
  }
  const savedAppsRef = useRef<SavedApp[]>([])


  useEffect(() => {
    selectedLanguageRef.current = selectedLanguage
  }, [selectedLanguage])

  const { darkMode, setDarkMode } = useDarkMode()

  const { handleMouseDown: handleResizeMouseDown } = useResizing(setPreviewWidth, setIsResizing)
  
  useKeyboardShortcuts(
    showSettings, setShowSettings,
    showPreview, setShowPreview,
    showAppDrawer, setShowAppDrawer,
    setContextMenu, setLongPressedApp,
    savedApps, galleryIndex, setGalleryIndex
  )

  const {
    messages: allMessages,
    input,
    setInput,
    setMessages,
    isLoading: isGenerating,
    append,
    stop: stopChat,
  } = useChat({
    key: chatKey,
    api: "/api/chat",
    initialMessages: initialMessages,
    body: () => {
      const b = { selectedProvider, selectedLanguage, purpose: purposeRef.current }
      return b
    },
    onError: (error) => {
      console.error("Chat error:", error)
      setStatus("error")
    },
    onFinish: () => {
      if (isBuilding) setStatus("ready")
      isSendingRef.current = false
      setIsSending(false)
      const lastMsg = allMessages[allMessages.length - 1] as any
      if (lastMsg?.imageUrl) {
        setStatus("idle")
      } else if (lastMsg?.audioUrl) {
        setStatus("idle")
      }
      if ((window as any).__performanceMetrics) {
        ;(window as any).__performanceMetrics.messages = allMessages.length
      }
    },
    onToolCall: (params) => {
       if (params.toolCall.toolName === "announce") {
         const { phase } = params.toolCall.args as any
         setStatus(phase as AgentStatus)
       }
     },
   })

  // Cap messages to last 50 to prevent OOM on long chats
  const messages = useMemo(() => allMessages.slice(-50), [allMessages])
  const messagesRef = useRef(messages)
  useEffect(() => { messagesRef.current = messages }, [messages])

  // Cache last user message index to avoid O(n²) findLastIndex
  const isLatestUserRef = useRef(false)
  useEffect(() => {
    const lastIdx = messages.findLastIndex((m: any) => m.role === 'user')
    isLatestUserRef.current = messages.length > 0 && messages.length - 1 === lastIdx
  }, [messages])

  // Auto scroll: enabled by default, disabled when user scrolls up, re-enabled on new message
  useEffect(() => {
    if (messages.length === 0) return
    requestAnimationFrame(() => {
      if (autoScrollRef.current) {
        messagesEndRef.current?.scrollIntoView({ behavior: "smooth", block: "end" })
      }
    })
  }, [messages])

  // Scroll listener: track if user is at bottom, release auto-scroll on manual scroll
  useEffect(() => {
    const onScroll = () => {
      const viewport = document.querySelector('[data-radix-scroll-area-viewport]') as HTMLElement | null
      if (!viewport) return

      const { scrollTop, scrollHeight, clientHeight } = viewport
      isAtBottomRef.current = scrollHeight - scrollTop - clientHeight < 80

      // Release auto-scroll if user scrolled up
      if (!isAtBottomRef.current) {
        autoScrollRef.current = false
      }
    }

    // Use MutationObserver to catch viewport appearing
    const observer = new MutationObserver(() => {
      const viewport = document.querySelector('[data-radix-scroll-area-viewport]') as HTMLElement | null
      if (viewport) {
        viewport.addEventListener('scroll', onScroll, { passive: true })
      }
    })
    observer.observe(document.body, { childList: true, subtree: true })

    // Also try immediately
    const viewport = document.querySelector('[data-radix-scroll-area-viewport]') as HTMLElement | null
    if (viewport) {
      viewport.addEventListener('scroll', onScroll, { passive: true })
    }

    return () => {
      observer.disconnect()
      const vp = document.querySelector('[data-radix-scroll-area-viewport]') as HTMLElement | null
      if (vp) vp.removeEventListener('scroll', onScroll)
    }
  }, [])

  // Save messages to localStorage
  useEffect(() => {
    if (messages.length > 0) {
      localStorage.setItem("chatMessages", JSON.stringify(messages))
    }
  }, [messages])

  // Persistence and loading effects
  useEffect(() => {
    const savedShowPreview = localStorage.getItem("showPreview")
    const savedShowSettings = localStorage.getItem("showSettings")
    if (savedShowPreview !== null) setShowPreview(savedShowPreview === "true")
    if (savedShowSettings !== null) setShowSettings(savedShowSettings === "true")
    
    const savedRecentChats = localStorage.getItem("recentChats")
    if (savedRecentChats) {
      try {
        setRecentChats(JSON.parse(savedRecentChats))
      } catch (e) { console.error("Failed to load recent chats") }
    }

    const savedLanguage = localStorage.getItem("selectedLanguage")
    if (savedLanguage !== null) setSelectedLanguage(savedLanguage)
  }, [])

  useEffect(() => {
    localStorage.setItem("showPreview", showPreview.toString())
  }, [showPreview])

  useEffect(() => {
    localStorage.setItem("showSettings", showSettings.toString())
  }, [showSettings])

  useEffect(() => {
    localStorage.setItem("selectedLanguage", selectedLanguage)
  }, [selectedLanguage])

  useEffect(() => {
    setHasSavedToGallery(false)
    const loadSavedApps = async () => {
      const savedAppsData = await getAllAppsFromDB()
      const appsWithUrls = savedAppsData.map(app => {
        if (app.code.startsWith('data:image/')) {
          return { ...app, url: app.code }
        }
        try {
          const blob = new Blob([app.code], { type: 'text/html' })
          return { ...app, url: URL.createObjectURL(blob) }
        } catch (e) { return app }
      })
      setSavedApps(appsWithUrls)
    }
    loadSavedApps()
  }, [])

  const regeneratePreviewsFromMessages = (msgs: any[]) => {
    const newPreviews = new Map<number, string>()
    msgs.forEach((message, i) => {
      if (message.role === 'assistant' && message.content) {
        const code = extractHtmlCode(message)
        if (code) {
          newPreviews.set(i, createBlobUrl(code))
        }
      }
    })
    setMessagePreviews(newPreviews)
  }

  // Lazy preview URL — creates blob URL only when needed
  const getPreviewUrl = useCallback((message: any) => {
    const code = extractHtmlCode(message)
    return code ? createBlobUrl(code) : null
  }, [])

  const extractCodeFromMessage = extractHtmlCode

  const handleSaveFromChat = async (msgIndex: number) => {
    const msg = messages[msgIndex]
    const code = extractCodeFromMessage(msg)
    if (!code) return

    // Use user message (not assistant response) for naming
    const userMsg = messages.slice(0, msgIndex).reverse().find(m => m.role === 'user')
    const userContent = userMsg?.content || msg.content || ''
    let appName = generateAppName(userContent)

    // LLM generates clean 1-2 word app name (non-blocking, saves after)
    let llmNamePromise: Promise<string | null> = Promise.resolve(null)
    try {
      llmNamePromise = (async () => {
        const res = await fetch('/api/chat', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            messages: [
              { role: 'system', content: 'You are a naming assistant. Given a user request to build something, output ONLY a clean 1-2 word app name. No quotes, no explanation. Examples: "make a calculator" → "Calculator", "build a sudoku game" → "Sudoku Game", "create a todo list" → "Todo List".' },
              { role: 'user', content: userContent },
            ],
            isAutonomous: false,
          }),
        })
        const reader = res.body?.getReader()
        if (!reader) return null
        const dec = new TextDecoder()
        let name = ''
        while (true) {
          const { done, value } = await reader.read()
          if (done) break
          const text = dec.decode(value)
          for (const line of text.split('\n')) {
            const trimmed = line.trim()
            if (!trimmed) continue
            // AI SDK v4 binary text format: 0:"text"
            if (trimmed.startsWith('0:')) {
              try {
                const t = JSON.parse(trimmed.slice(2))
                if (typeof t === 'string') name += t
              } catch {}
            }
            // Legacy: {"type":"text-delta","textDelta":"..."}
            else if (trimmed.startsWith('{')) {
              try {
                const j = JSON.parse(trimmed)
                if (j.type === 'text-delta' && j.textDelta) name += j.textDelta
              } catch {}
            }
          }
          if (name.length > 100) break
        }
        const clean = name.trim().replace(/["'\n\r]/g, '').trim().split(/[\s,]+/).slice(0, 2).join(' ')
        return (clean && clean.length > 0 && clean.length < 30) ? clean : null
      })()
    } catch {}

    const existingApp = savedApps.find(app => app.code === code)
    if (existingApp) return

    const newApp: SavedApp = {
      id: Date.now().toString(),
      name: appName,
      icon: getAppIcon(appName),
      code: code,
      url: "",
      chatMessages: messages,
      createdAt: Date.now()
    }
    await saveAppToDB(newApp)
    const blob = new Blob([code], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const appWithUrl = { ...newApp, url }
    setSavedApps(prev => [appWithUrl, ...prev])

    // Update name once LLM responds
    if (llmNamePromise) {
      llmNamePromise.then(llmName => {
        if (llmName && llmName !== appName) {
          setSavedApps(prev => prev.map(a => a.id === newApp.id ? { ...a, name: llmName, icon: getAppIcon(llmName) } : a))
          saveAppToDB({ ...newApp, name: llmName }).catch(() => {})
        }
      })
    }
  }

  const handleDownloadFromChat = (msgIndex: number) => {
    const msg = messages[msgIndex]
    const code = extractCodeFromMessage(msg)
    if (!code) return

    const zip = new JSZip()
    zip.file("index.html", wrapHtml(code))
    zip.generateAsync({ type: "blob" }).then((content) => {
      const url = URL.createObjectURL(content)
      const link = document.createElement('a')
      link.href = url
      link.download = `app-${Date.now()}.zip`
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      URL.revokeObjectURL(url)
    })
  }

  const handleImageSaveFromChat = async (msgIndex: number) => {
    const msg = messages[msgIndex]
    const imageUrl = messageImages.get(msgIndex) || (msg as any).imageUrl
    if (!imageUrl) return

    const msgContent = msg.content || ''
    const promptMatch = msgContent.match(/IMAGE_REQUEST:\s*(.+)/i)
    const rawPrompt = promptMatch ? promptMatch[1].trim() : 'Image'
    const appName = generateAppName(rawPrompt, "Image")

    const existingApp = savedApps.find(app => app.url === imageUrl)
    if (existingApp) return

    try {
      let base64: string
      if (imageUrl.startsWith('data:')) {
        base64 = imageUrl
      } else {
        const response = await fetch(imageUrl)
        const blob = await response.blob()
        base64 = await new Promise<string>((resolve, reject) => {
          const reader = new FileReader()
          reader.onloadend = () => resolve(reader.result as string)
          reader.onerror = reject
          reader.readAsDataURL(blob)
        })
      }
      const newApp: SavedApp = {
        id: Date.now().toString(),
        name: appName,
        icon: "🖼️",
        code: base64,
        url: imageUrl,
        createdAt: Date.now()
      }
      await saveAppToDB(newApp)
      setSavedApps(prev => [newApp, ...prev])
    } catch (error) {
      console.error("Failed to save image:", error)
    }
  }

  const handleImageDownloadFromChat = async (msgIndex: number) => {
    const msg = messages[msgIndex]
    const imageUrl = messageImages.get(msgIndex) || (msg as any).imageUrl
    if (!imageUrl) return

    const msgContent = msg.content || ''
    const promptMatch = msgContent.match(/IMAGE_REQUEST:\s*(.+)/i)
    const rawPrompt = promptMatch ? promptMatch[1].trim() : 'image'
    const fileName = generateFileName(rawPrompt)

    const extension = imageUrl.includes('image/png') ? 'png' : 'jpg'
    const link = document.createElement('a')
    link.href = imageUrl
    link.download = `${fileName}-${Date.now()}.${extension}`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  }

  const handleImageOpenFromChat = (msgIndex: number) => {
    const imageUrl = messageImages.get(msgIndex) || (messages[msgIndex] as any).imageUrl
    if (!imageUrl) return
    setPreviewImageUrl(imageUrl)
    setShowPreview(true)
  }

  const savedCodeSet = useMemo(() => new Set(savedApps.map(a => a.code)), [savedApps])
  const isAppSavedInChat = (msgIndex: number): boolean => {
    const code = extractCodeFromMessage(messages[msgIndex])
    return !!code && savedCodeSet.has(code)
  }

  const isImageSavedInChat = (msgIndex: number): boolean => {
    const imageUrl = messageImages.get(msgIndex)
    if (!imageUrl) return false
    return savedApps.some(app => app.url === imageUrl || app.code === imageUrl)
  }

  useEffect(() => {
    if (currentChatMessages.length > 0) {
      setInitialMessages(currentChatMessages)
      setInput("")
    } else {
      const savedMessagesData = localStorage.getItem("chatMessages")
      if (savedMessagesData) {
        try {
          const messagesData = JSON.parse(savedMessagesData)
          if (messagesData.length > 0) {
            setInitialMessages(messagesData)
            setInput("")
          }
        } catch (e) { console.error("Failed to load chat messages") }
      }
    }
  }, [currentChatMessages])

  useEffect(() => {
    const prev = savedAppsRef.current
    savedAppsRef.current = savedApps
    if (prev.length === 0) return
    const newApps = savedApps.filter(a => !prev.some(p => p.id === a.id))
    const changedIds = new Set(savedApps.filter(a => {
      const p = prev.find(pp => pp.id === a.id)
      return !!p && p.code !== a.code
    }).map(a => a.id))
    // Save only new or changed apps
    const toSave = [...newApps, ...savedApps.filter(a => changedIds.has(a.id))]
    toSave.forEach(app => saveAppToDB({ ...app, url: "" }))
  }, [savedApps])

useEffect(() => {
    if (!currentChatId || messages.length === 0) return
    const recentMessages = messages.slice(-20)

    const userMessages = recentMessages.filter(m => m.role === 'user')
    if (userMessages.length > 0) {
      const lastUserMsg = userMessages[userMessages.length - 1]
      const title = lastUserMsg.content?.substring(0, 40).replace(/[^a-zA-Z0-9 ]/g, ' ').trim() || 'New Chat'

      saveChatHistoryToDB(currentChatId, recentMessages).catch(() => {})

      setRecentChats(prev => {
        const existingIndex = prev.findIndex(c => c.id === currentChatId)
        let updated
        if (existingIndex >= 0) {
          updated = prev.map((c, i) => i === existingIndex ? { ...c, title, timestamp: Date.now() } : c)
        } else {
          const filtered = prev.filter(c => c.title !== title)
          const newChat = { id: currentChatId, title, timestamp: Date.now() }
          updated = [newChat, ...filtered].slice(0, 10)
        }
        try {
          localStorage.setItem("recentChats", JSON.stringify(updated))
        } catch (e) {
          // Ignore if recentChats fails
        }
        return updated
      })
    }
  }, [messages, currentChatId])

  useEffect(() => {
    const urlParams = new URLSearchParams(window.location.search)
    const encodedApp = urlParams.get('app')
    if (encodedApp) {
      try {
        const decoded = JSON.parse(atob(encodedApp))
        const sharedApp: SavedApp = {
          id: Date.now().toString(),
          name: decoded.name || 'Shared App',
          icon: decoded.icon || '📱',
          code: decoded.code,
          url: '',
          chatMessages: decoded.chatMessages,
          createdAt: decoded.createdAt || Date.now()
        }
        setInitialMessages(decoded.chatMessages || [])
        setCurrentChatMessages(decoded.chatMessages || [])
        setLocalPreviewCode(decoded.code)
        setEditedAppCode(decoded.code)
        setShowPreview(true)
        setShowAppDrawer(false)
        setBlobUrl("")
        setTimeout(() => {
          setBlobUrl(createBlobUrl(decoded.code, sharedApp.name))
        }, 0)
        window.history.replaceState({}, '', window.location.pathname)
      } catch (error) {
        console.error("Failed to load shared app:", error)
      }
    }
  }, [])

  useEffect(() => {
    if (shareMessage) {
      const timer = setTimeout(() => setShareMessage(""), 3000)
      return () => clearTimeout(timer)
    }
  }, [shareMessage])

  useEffect(() => {
    return () => {
      savedApps.forEach(app => { if (app.url) URL.revokeObjectURL(app.url) })
    }
  }, [savedApps])

  useEffect(() => {
    const newImages = new Map<number, string>()
    messages.forEach((msg, i) => {
      if (msg.role === 'assistant' && msg.content) {
        const imageMatch = msg.content.match(/@image\[([^\]]+)\]/)
        if (imageMatch) {
          newImages.set(i, imageMatch[1])
        }
      }
      if (msg.role === 'assistant' && (msg as any).imageUrl) {
        newImages.set(i, (msg as any).imageUrl)
      }
    })
    if (newImages.size > 0) {
      setMessageImages(prev => {
        const updated = new Map(prev)
        newImages.forEach((url, idx) => updated.set(idx, url))
        return updated
      })
    }
  }, [messages])

  useEffect(() => {
    async function loadProviders() {
      try {
        const res = await fetch("/api/router")
        const data = await res.json()
        const textProviders = data.text_generation || []
        setProviders(textProviders)
        const routerProvider = textProviders.find((p: Provider) => p.router === true)
        if (routerProvider) setSelectedProvider(routerProvider.name)
      } catch (error) {
        console.error("Failed to load providers:", error)
      } finally {
        setLoadingProviders(false)
      }
    }
    loadProviders()
  }, [])

  const handleConsoleMessage = (msg: string) => {
    window.dispatchEvent(new CustomEvent("addErrorToFixer", { detail: msg }))
  }

  const stopGeneration = () => {
    stopChat()
    if (abortControllerRef.current) {
      abortControllerRef.current.abort()
      abortControllerRef.current = null
    }
    // Clean up preview resources
    if (blobUrl) {
      URL.revokeObjectURL(blobUrl)
      setBlobUrl("")
    }
    setLocalPreviewCode("")
    setIsBuilding(false)
    setIsSending(false)
    isSendingRef.current = false
    setStatus("idle")
  }

const handleSubmit = async (userText: string, e?: React.FormEvent, language?: string) => {
    if (e) e.preventDefault()
    if (!userText.trim() || isGenerating || isImageGenerating) return
    setIsSending(true)
    isSendingRef.current = true
    setInput("")
    autoScrollRef.current = true
    requestAnimationFrame(() => {
      messagesEndRef.current?.scrollIntoView({ behavior: "smooth", block: "end" })
    })

    setLocalPreviewCode("")
    setBlobUrl("")
    setStatus("planning")
    setIsBuilding(true)
    setHasSavedToGallery(false)
    setSessionApps([])
    setCurrentAppIndex(-1)
    setAutoGenerated(false)

    // Client-side regex intent detection (instant, no LLM call)
    const fullIntent = detectIntent(userText, selectedLanguage)
    console.log('[debug] intent=%s confidence=%s reasoning=%s scores=%o', fullIntent.intent, fullIntent.confidence, fullIntent.reasoning, fullIntent.scores)
    const hasImage = detectImageIntent(userText, selectedLanguage)
    const hasAudio = detectAudioIntent(userText, selectedLanguage)
    const hasApp = detectAppIntent(userText, selectedLanguage)
    const hasWeather = detectWeatherIntent(userText, selectedLanguage)
    const hasCricket = detectCricketIntent(userText, selectedLanguage)
    const hasNews = detectNewsIntent(userText, selectedLanguage)

    // Determine purpose: app building vs general chat
    const isAppBuilding = hasApp
    setPurposeImmediate(isAppBuilding ? "app" : "general")

    if (hasImage && hasAudio) {
      // Ambiguous: ask for clarification
      const clarMsgId = (Date.now() + 1).toString()
      setMessages(prev => [...prev,
        { id: Date.now().toString(), role: "user" as const, content: userText },
        { id: clarMsgId, role: "assistant" as const, content: "I'm not sure what you'd like. Could you clarify?\n\n- 📷 **Image**: \"show me a photo of...\", \"draw a...\", \"generate an image...\"\n- 🎵 **Audio**: \"generate audio...\", \"text to speech...\", \"create a song...\"\n- 💬 **Chat**: Ask a question, request an app, or just chat" }
      ])
      autoScrollRef.current = true
      setTimeout(() => {
        scrollToBottom()
      }, 50)
      setIsSending(false)
      isSendingRef.current = false
      setIsBuilding(false)
      setStatus("idle")
      return
    }

    // Create chat ID for new chats (only for actual chats)
    if (!currentChatId) {
      setCurrentChatId(Date.now().toString())
    }

    // Multi-intent: text + image
    const multiIntent = detectMultiIntent(userText, selectedLanguage)
    const hasText = multiIntent.intents.includes('text')
    const multiImage = multiIntent.intents.includes('image')

    // Build user message object for fetch calls (used by multi-intent/image/audio branches)
    const userMsg = { role: "user" as const, content: userText, id: Date.now().toString() } as any

    if (multiImage && hasText) {
      setMessages(prev => [...prev, userMsg])
      autoScrollRef.current = true
      setTimeout(() => {
        scrollToBottom()
      }, 50)
      setIsImageGenerating(true)
      try {
        // Get image from router, text from chat
        const [imgRes, chatRes] = await Promise.all([
          fetch('/api/router', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ message: userText, selectedLanguage, messages: [...messages, userMsg] }),
          }),
          fetch('/api/chat', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ messages: [...messages, userMsg], isAutonomous: false, selectedLanguage, purpose: purposeRef.current }),
          }),
        ])
        const imgData = await imgRes.json()
        if (imgData.imageUrl) {
          setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: "assistant", content: "", imageUrl: imgData.imageUrl }] as any)
        } else if (imgData.error) {
          setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: "assistant", content: `Image generation failed: ${imgData.error}` }] as any)
        }
        // Handle streaming chat response
        if (chatRes.ok) {
          const reader = chatRes.body?.getReader()
          if (reader) {
            const decoder = new TextDecoder()
            let fullResponse = ''
            let buffer = ''
            while (true) {
              const { done, value } = await reader.read()
              if (done) break
              buffer += decoder.decode(value, { stream: true })
              const lines = buffer.split('\n')
              buffer = lines.pop() || ''
              for (const line of lines) {
                const trimmed = line.trim()
                if (!trimmed) continue
                // AI SDK v4 binary text format: 0:"text"
                if (trimmed.startsWith('0:')) {
                  try {
                    const t = JSON.parse(trimmed.slice(2))
                    if (typeof t === 'string') fullResponse += t
                  } catch {}
                }
                // Legacy: data: {"type":"text-delta","textDelta":"..."}
                else if (trimmed.startsWith('data:')) {
                  const d = trimmed.slice(5).trim()
                  if (d) {
                    try {
                      const j = JSON.parse(d)
                      if (j.type === 'text-delta' && j.textDelta) fullResponse += j.textDelta
                    } catch {}
                  }
                }
                // Legacy: {"type":"text-delta","textDelta":"..."}
                else if (trimmed.startsWith('{')) {
                  try {
                    const j = JSON.parse(trimmed)
                    if (j.type === 'text-delta' && j.textDelta) fullResponse += j.textDelta
                  } catch {}
                }
              }
            }
            if (buffer) {
              const trimmed = buffer.trim()
              if (trimmed.startsWith('0:')) {
                try {
                  const t = JSON.parse(trimmed.slice(2))
                  if (typeof t === 'string') fullResponse += t
                } catch {}
              } else if (trimmed.startsWith('data:')) {
                const d = trimmed.slice(5).trim()
                if (d) {
                  try {
                    const j = JSON.parse(d)
                    if (j.type === 'text-delta' && j.textDelta) fullResponse += j.textDelta
                  } catch {}
                }
              } else if (trimmed.startsWith('{')) {
                try {
                  const j = JSON.parse(trimmed)
                  if (j.type === 'text-delta' && j.textDelta) fullResponse += j.textDelta
                } catch {}
              }
            }
            if (fullResponse) {
              setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: "assistant", content: fullResponse }] as any)
            }
          }
        }
      } catch (err) {
        console.error("Multi-intent failed:", err)
        setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: "assistant", content: "Multi-intent request failed." }] as any)
      }
      setIsImageGenerating(false)
      setIsSending(false)
      isSendingRef.current = false
      setIsBuilding(false)
      setStatus("idle")
      return
    }

      // Route to image generation
    if (multiIntent.intents.includes("image")) {
      setMessages(prev => [...prev, userMsg])
      autoScrollRef.current = true
      setTimeout(() => {
        scrollToBottom()
      }, 50)
      setIsImageGenerating(true)
      try {
        const res = await fetch('/api/router', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ message: userText, selectedLanguage, messages: [...messages, userMsg] }),
        })
        const data = await res.json()
        if (data.imageUrl) {
          setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: "assistant", content: "", imageUrl: data.imageUrl }] as any)
        } else if (data.error) {
          setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: "assistant", content: `Image generation failed: ${data.error}` }] as any)
        }
      } catch (err) {
        console.error("Image generation failed:", err)
        setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: "assistant", content: "Image generation failed. Please check the image provider settings." }] as any)
      }
      setIsImageGenerating(false)
      setIsSending(false)
      isSendingRef.current = false
      setIsBuilding(false)
      setStatus("idle")
      return
    }

  // Route to audio generation
    if (multiIntent.intents.includes("audio")) {
      setMessages(prev => [...prev, userMsg])
      autoScrollRef.current = true
      setTimeout(() => {
        scrollToBottom()
      }, 50)
      setIsImageGenerating(true)
      try {
        const res = await fetch('/api/router', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ message: userText, selectedLanguage, messages: [...messages, userMsg] }),
        })
        const data = await res.json()
        if (data.audioUrl) {
          setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: "assistant", content: "", audioUrl: data.audioUrl }] as any)
        } else if (data.error) {
          setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: "assistant", content: `Audio generation failed: ${data.error}` }] as any)
        }
      } catch (err) {
        console.error("Audio generation failed:", err)
        setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: "assistant", content: "Audio generation failed. Please check the audio provider settings." }] as any)
      }
      setIsImageGenerating(false)
      setIsSending(false)
      isSendingRef.current = false
      setIsBuilding(false)
      setStatus("idle")
      return
    }

    // Route to weather tool
    console.log('[chat] hasWeather=%s hasImage=%s hasAudio=%s hasApp=%s', hasWeather, hasImage, hasAudio, hasApp)
    if (hasWeather) {
      // Extract city: strip weather keywords (English + romanized multilingual), take remaining words as city
      let city = "Delhi"
      const cleaned = userText.toLowerCase()
        .replace(/\b(?:temperature|weather|mausam|mausum|mosam|tapman|tapmān|tapamatra|abohawa|vaatavaranam|ushnograta|kalanilai|havamana|darja\s+hararat|how\s+is\s+the\s+weather|what\s+is\s+the\s+temperature|check\s+(?:the\s+)?weather|show\s+(?:me\s+)?(?:the\s+)?weather|show\s+me\s+the\s+temperature|check\s+temperature|tell\s+me\s+the\s+weather|tell\s+me\s+the\s+temperature|show\s+me\s+an?\s+weather)\s*/gi, '')
        .replace(/\b(?:in|for|please|can|you|tell|me|show|check|what|is|the|how|at|it|kaise|hai|hai\s+ki|ka|ki|ke|se|mein|mein|rain|raining|will|going|to)\b\s*/gi, ' ')
        .replace(/\s+/g, ' ')
        .replace(/[?!.]/g, '')
        .trim()
      if (cleaned.length > 0 && cleaned.length < 30) {
        city = cleaned.charAt(0).toUpperCase() + cleaned.slice(1)
      }

      // Check for rain query: "is it raining", "will it rain", etc. → plain text answer
      const rainMatch = userText.toLowerCase().match(/\b(is it raining|is it rain|will it rain|going to rain)\b/)
      if (rainMatch) {
        setMessages(prev => [...prev, userMsg])
        autoScrollRef.current = true
        setTimeout(() => scrollToBottom(), 50)
        setIsSending(true)
        try {
          const res = await fetch(`/api/tools/weather?city=${encodeURIComponent(city)}&mode=rain`)
          const data = await res.json()
          setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: "assistant", content: data.answer || "Weather data unavailable." }] as any)
        } catch (err) {
          console.error("Rain query failed:", err)
          setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: "assistant", content: "Weather data unavailable." }] as any)
        }
        setIsSending(false)
        isSendingRef.current = false
        setStatus("idle")
        return
      }

      // Full weather card path
      try {
        const res = await fetch(`/api/tools/weather?city=${encodeURIComponent(city)}`)
        const data = await res.json()
        if (data.structured) {
          setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: "assistant", content: data.result, weatherData: data.structured }] as any)
        } else if (data.error) {
          setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: "assistant", content: `Weather error: ${data.error}` }] as any)
        }
      } catch (err) {
        console.error("Weather fetch failed:", err)
        setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: "assistant", content: "Weather data unavailable." }] as any)
      }
      setIsSending(false)
      isSendingRef.current = false
      setStatus("idle")
      return
    }

    // Route to cricket tool
    if (hasCricket) {
      setMessages(prev => [...prev, userMsg])
      autoScrollRef.current = true
      setTimeout(() => scrollToBottom(), 50)
      setIsSending(true)
      try {
        const res = await fetch(`/api/tools/cricket?match=live`)
        const data = await res.json()
        if (data.structured) {
          const cd = data.structured as CricketMatchData
          setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: "assistant", content: data.result, cricketData: cd }] as any)
        } else if (data.error) {
          setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: "assistant", content: `Cricket error: ${data.error}` }] as any)
        }
      } catch (err) {
        console.error("Cricket fetch failed:", err)
        setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: "assistant", content: "Cricket data unavailable." }] as any)
      }
      setIsSending(false)
      isSendingRef.current = false
      setStatus("idle")
      return
    }

    // Route to news tool
    if (hasNews) {
      setMessages(prev => [...prev, userMsg])
      autoScrollRef.current = true
      setTimeout(() => scrollToBottom(), 50)
      setIsSending(true)
      try {
        const res = await fetch(`/api/tools/news?category=top&limit=10`)
        const data = await res.json()
        if (data.structured) {
          const nd: NewsCardData = { query: "Latest News", articles: data.structured, totalResults: data.structured.length }
          setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: "assistant", content: data.result, newsData: nd }] as any)
        } else if (data.error) {
          setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: "assistant", content: `News error: ${data.error}` }] as any)
        }
      } catch (err) {
        console.error("News fetch failed:", err)
        setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: "assistant", content: "News data unavailable." }] as any)
      }
      setIsSending(false)
      isSendingRef.current = false
      setStatus("idle")
      return
    }

    // Text streaming (app building / chat) — use append (handles message + streaming)
    if (isAppBuilding) {
      // Non-streaming for app building: streaming causes 500+ re-renders per response
      // (every token triggers full message list render + blob URL creation)
      setMessages(prev => [...prev, { id: Date.now().toString(), role: "user", content: userText }])
      autoScrollRef.current = true
      setTimeout(() => scrollToBottom(), 50)

      const res = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          messages: [...messages, { role: "user", content: userText }],
          isAutonomous: false,
          selectedLanguage,
          purpose: "app",
        }),
      })

      if (res.ok) {
        const reader = res.body?.getReader()
        if (reader) {
          const decoder = new TextDecoder()
          let fullResponse = ''
          let buffer = ''
          while (true) {
            const { done, value } = await reader.read()
            if (done) break
            buffer += decoder.decode(value, { stream: true })
            const lines = buffer.split('\n')
            buffer = lines.pop() || ''
            for (const line of lines) {
              const trimmed = line.trim()
              if (!trimmed) continue

              // AI SDK v4 binary text format: 0:"text", f:{...}, 9:{...}, a:{...}, e:{...}
              if (trimmed.startsWith('0:')) {
                try {
                  const text = JSON.parse(trimmed.slice(2))
                  if (typeof text === 'string') fullResponse += text
                } catch { /* skip */ }
              }
              // Legacy SSE format: data: {"type":"text-delta","textDelta":"..."}
              else if (trimmed.startsWith('data:')) {
                const data = trimmed.slice(5).trim()
                if (!data) continue
                try {
                  const j = JSON.parse(data)
                  if (j.type === 'text-delta' && j.textDelta) fullResponse += j.textDelta
                } catch { /* skip */ }
              }
            }
          }
          // Handle remaining buffer
          if (buffer) {
            const trimmed = buffer.trim()
            if (trimmed.startsWith('0:')) {
              try {
                const text = JSON.parse(trimmed.slice(2))
                if (typeof text === 'string') fullResponse += text
              } catch {}
            } else if (trimmed.startsWith('data:')) {
              const data = trimmed.slice(5).trim()
              if (data) {
                try {
                  const j = JSON.parse(data)
                  if (j.type === 'text-delta' && j.textDelta) fullResponse += j.textDelta
                } catch {}
              }
            }
          }
          if (fullResponse) {
            setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: "assistant", content: fullResponse }] as any)
          } else {
            console.warn('[chat] app building: empty response')
          }
        }
      } else {
        const body = await res.text().catch(() => '')
        console.error('[chat] app building failed:', res.status, body.slice(0, 500))
        setMessages(prev => [...prev, { id: (Date.now() + 1).toString(), role: "assistant", content: `Chat error: ${res.status} ${res.statusText}` }] as any)
      }
      setIsSending(false)
      isSendingRef.current = false
      setIsBuilding(false)
      setStatus("idle")
    } else {
      await append({ role: "user", content: userText })
      // Scroll to show user message, enable auto-scroll for incoming response
      autoScrollRef.current = true
      setTimeout(() => {
        scrollToBottom()
      }, 50)
    }
  }

  function getAppIcon(appName: string): string {
    const lowered = appName.toLowerCase()
    if (lowered.includes('sudoku') || lowered.includes('puzzle')) return '🧩'
    if (lowered.includes('todo') || lowered.includes('task')) return '✅'
    if (lowered.includes('calc')) return '🔢'
    if (lowered.includes('note')) return '📝'
    if (lowered.includes('clock')) return '⏰'
    if (lowered.includes('weather')) return '🌤️'
    if (lowered.includes('game')) return '🎮'
    if (lowered.includes('photo') || lowered.includes('image')) return '📷'
    if (lowered.includes('music')) return '🎵'
    if (lowered.includes('contact')) return '📱'
    if (lowered.includes('shop') || lowered.includes('cart')) return '🛒'
    if (lowered.includes('food')) return '🍳'
    if (lowered.includes('chat')) return '💬'
    if (lowered.includes('fitness')) return '💪'
    if (lowered.includes('travel')) return '✈️'
    if (lowered.includes('book')) return '📚'
    if (lowered.includes('video')) return '🎬'
    if (lowered.includes('camera')) return '📸'
    if (lowered.includes('map')) return '🗺️'
    if (lowered.includes('bank') || lowered.includes('money')) return '💰'
    if (lowered.includes('art')) return '🎨'
    return '📱'
  }

  useEffect(() => {
    const code = findLatestHtmlCode(messages)
    if (code) setLocalPreviewCode(code)
  }, [messages])

  // Defer blob URL creation to avoid blocking the main thread during response reading
  const pendingBlobUrlRef = useRef<string | null>(null)
  useEffect(() => {
    if (!localPreviewCode) return
    // Revoke previous blob URL
    if (pendingBlobUrlRef.current) {
      URL.revokeObjectURL(pendingBlobUrlRef.current)
      pendingBlobUrlRef.current = null
    }
    // Create blob URL asynchronously to avoid blocking
    const timer = setTimeout(() => {
      const url = createBlobUrl(localPreviewCode)
      setBlobUrl(url)
      pendingBlobUrlRef.current = url
      if ((performance as any).memory) {
        ;(window as any).__performanceMetrics.blobUrls = pendingBlobUrlRef.current ? 1 : 0
        ;(window as any).__performanceMetrics.heapAfter = (performance as any).memory.usedJSHeapSize / 1024 / 1024
      }
      // Find the assistant message that contains this code and store preview
      const msgs = messagesRef.current
      for (let i = msgs.length - 1; i >= 0; i--) {
        const code = extractHtmlCode(msgs[i])
        if (code === localPreviewCode) {
          setMessagePreviews(prev => new Map(prev).set(i, url))
          break
        }
      }
    }, 0)
    return () => { clearTimeout(timer) }
  }, [localPreviewCode])

  useEffect(() => {
    if (status === "ready" && localPreviewCode && autoGenerated) {
      const lastUserMsg = messages.filter(m => m.role === 'user').pop()
      const rawName = lastUserMsg?.content?.substring(0, 50) || 'My App'
      const appName = generateAppName(rawName)
      const newApp: SavedApp = {
        id: Date.now().toString() + Math.random().toString(36).substr(2, 9),
        name: appName,
        icon: getAppIcon(appName),
        code: localPreviewCode,
        url: "",
        createdAt: Date.now()
      }
      setSessionApps(prev => [...prev.filter(a => a.code !== localPreviewCode), newApp])
      setCurrentAppIndex(prev => prev + 1)
      setIsBuilding(false)
    }
  }, [status, localPreviewCode, messages])

  useEffect(() => {
    const code = findLatestHtmlCode(messages)
    if (code && !autoGenerated) {
      const isSessionApp = sessionApps.some(app => app.code === code)
      if (!isSessionApp) {
        setLocalPreviewCode(code)
        setAutoGenerated(true)
      }
    }
  }, [messages])

  // Blob URL creation deferred to avoid blocking main thread


  const openSavedApp = (app: SavedApp) => {
    setLocalPreviewCode(app.code)
    setShowPreview(true)
    setShowAppDrawer(false)
    setBlobUrl("")
    setInput("")
    setTimeout(() => {
      setBlobUrl(createBlobUrl(app.code, app.name))
    }, 0)
  }

  const handleEditApp = async (app: SavedApp) => {
    setIsEditing(false)
    setLocalPreviewCode(app.code)
    setEditedAppCode(app.code)
    setShowPreview(true)
    setShowAppDrawer(false)
    setBlobUrl("")
    setHasSavedToGallery(false)
    setTimeout(() => {
      setBlobUrl(createBlobUrl(app.code, `Edit: ${app.name}`))
    }, 0)
  }

  const handleSaveEditedApp = async () => {
    const updatedApp: SavedApp = {
      ...savedApps.find(app => app.code === editedAppCode)!,
      code: editedAppCode,
      chatMessages: messages,
      createdAt: Date.now()
    }
    await saveAppToDB(updatedApp)
    setSavedApps(prev => prev.map(app => app.id === updatedApp.id ? updatedApp : app))
    setIsEditing(false)
    setEditedAppCode("")
  }

  const removeApp = async (appId: string) => {
    await deleteAppFromDB(appId)
    setSavedApps(prev => prev.filter(a => a.id !== appId))
    setContextMenu(null)
    setLongPressedApp(null)
  }

  const handleLongPressStart = (app: SavedApp, e: any) => {
    if (e?.preventDefault) e.preventDefault()
    setLongPressedApp(app)
    setContextMenu(null)
    const timer = setTimeout(() => {
      const target = e?.target || document.activeElement
      const rect = (target as HTMLElement).getBoundingClientRect()
      setContextMenu({
        appId: app.id,
        x: rect.left,
        y: rect.bottom + 5
      })
    }, 500)
    setLongPressTimer(timer)
  }

  const handleLongPressEnd = () => {
    if (longPressTimer) clearTimeout(longPressTimer)
    setLongPressTimer(null)
    setContextMenu(null)
    setLongPressedApp(null)
  }

  const newSession = () => {
    const newChatId = Date.now().toString()
    setChatKey(prev => String(Number(prev) + 1))
    setCurrentChatId(newChatId)
    setCurrentChatMessages([])
    setInput("")
    setInitialMessages([])
    setStatus("idle")
    setIsBuilding(false)
    setLocalPreviewCode("")
    setEditedAppCode("")
    setIsEditing(false)
    setHasSavedToGallery(false)
    setSessionApps([])
    setCurrentAppIndex(-1)
    setMessagePreviews(new Map())
    setMessageImages(new Map())
    if (blobUrl) { URL.revokeObjectURL(blobUrl); setBlobUrl("") }
    localStorage.removeItem("chatMessages")
  }

  const [sessionApps, setSessionApps] = useState<SavedApp[]>([])
  const [currentAppIndex, setCurrentAppIndex] = useState(-1)
  const [activeChatTab, setActiveChatTab] = useState<string | null>(null)
  const [visibleRange, setVisibleRange] = useState({ start: 0, end: 50 })
  // Cleanup cached blob URLs when visible range changes
  useEffect(() => {
    previewCacheRef.current.clear()
  }, [visibleRange.start, visibleRange.end])

  useEffect(() => {
    if (sessionApps.length > 0) {
      setHasSavedToGallery(false)
    }
  }, [sessionApps, currentAppIndex])

  useEffect(() => {
    if (!showPreview) {
      setHasSavedToGallery(false)
    }
  }, [showPreview])

  const handleSaveToGallery = async () => {
    try {
      const codeToSave = localPreviewCode || (sessionApps[currentAppIndex]?.code ?? '')
      if (!codeToSave) {
        return
      }
      const lastUserMsg = messages.filter(m => m.role === 'user').pop()
      const appName = generateAppName(lastUserMsg?.content || '')
      const existingApp = savedApps.find(app => app.code === codeToSave)
      if (existingApp) {
        return
      }
      const newApp: SavedApp = {
        id: Date.now().toString(),
        name: appName,
        icon: getAppIcon(appName),
        code: codeToSave,
        url: "",
        chatMessages: messages,
        createdAt: Date.now()
      }
      await saveAppToDB(newApp)
      const blob = new Blob([codeToSave], { type: 'text/html' })
      const url = URL.createObjectURL(blob)
      const appWithUrl = { ...newApp, url }
      setSavedApps(prev => [appWithUrl, ...prev])
      setHasSavedToGallery(true)
    } catch (error) {
      console.error('Failed to save to gallery:', error)
    }
  }

  useEffect(() => {
    const totalMessages = messages.length
    if (totalMessages > 50) {
      setVisibleRange({ start: totalMessages - 50, end: totalMessages })
    } else {
      setVisibleRange({ start: 0, end: totalMessages })
    }
  }, [messages.length])

  const handleSwitchToSavedApp = (app: SavedApp) => {
    setIsEditing(false)
    setLocalPreviewCode(app.code)
    setEditedAppCode(app.code)
    setShowAppDrawer(false)
    setActiveChatTab(app.id)
    setBlobUrl("")
    setInput("")
    
    const isBase64Image = app.code.startsWith('data:image/')
    const isBase64Video = app.code.startsWith('data:video/')
    const isBase64Audio = app.code.startsWith('data:audio/')
    const isMediaFile = isBase64Image || isBase64Video || isBase64Audio
    
    if (isMediaFile) {
      setPreviewImageUrl(app.code)
      setShowPreview(true)
    } else {
      setPreviewImageUrl(null)
      setShowPreview(true)
      setTimeout(() => {
        setBlobUrl(createBlobUrl(app.code, app.name))
      }, 0)
    }
  }

  const handleShareApp = async (app: SavedApp) => {
    try {
      const shareData = {
        code: app.code,
        chatMessages: app.chatMessages,
        name: app.name,
        icon: app.icon,
        createdAt: app.createdAt
      }
      const encoded = btoa(JSON.stringify(shareData))
      const shareUrl = `${window.location.origin}${window.location.pathname}?app=${encoded}`
      setShareMessage(`Link copied to clipboard!`)
      await navigator.clipboard.writeText(shareUrl)
      setTimeout(() => setShareMessage(""), 3000)
    } catch (error) {
      console.error("Failed to share:", error)
      setShareMessage("Failed to copy link")
      setTimeout(() => setShareMessage(""), 3000)
    }
  }

  const handleDeleteApp = (appId: string) => {
    setSavedApps(prev => prev.filter(app => app.id !== appId))
  }

  const handleDownloadApp = (app: SavedApp) => {
    if (app.code.startsWith('data:image/') || app.code.startsWith('data:video/') || app.code.startsWith('data:audio/')) {
      const link = document.createElement('a')
      link.href = app.code
      link.download = `${app.name}.${app.code.split(';')[0].split('/')[1] || 'bin'}`
      link.click()
    }
  }

  const handleRunApp = (app: SavedApp) => {
    if (!app.code.startsWith('data:')) {
      setShowPreview(true)
      setPreviewImageUrl(null)
      setBlobUrl("")
      setTimeout(() => {
        setBlobUrl(createBlobUrl(app.code, app.name))
      }, 0)
    }
  }

  const handleNewChat = () => {
    newSession()
    setActiveChatTab(null)
  }

  const loadRecentChat = (chatId: string) => {
    const chat = recentChats.find(c => c.id === chatId)
    if (chat) {
      setCurrentChatId(chatId)
      getChatHistoryFromDB(chatId).then((savedMessagesData) => {
        if (savedMessagesData && savedMessagesData.length > 0) {
          setInitialMessages(savedMessagesData)
          setCurrentChatMessages(savedMessagesData)
        }
      })
    }
  }

  const deleteChat = (chatId: string) => {
    setRecentChats(prev => {
      const updated = prev.filter(c => c.id !== chatId)
      localStorage.setItem("recentChats", JSON.stringify(updated))
      return updated
    })
    deleteChatHistoryFromDB(chatId)
    if (currentChatId === chatId) {
      setCurrentChatId("")
      setCurrentChatMessages([])
      setMessages([])
      setInput("")
      setInitialMessages([])
      setLocalPreviewCode("")
      setMessagePreviews(new Map())
    }
  }

  const clearAllChats = () => {
    setMessages([])
    setChatKey(prev => String(Number(prev) + 1))
    setRecentChats([])
    localStorage.removeItem("recentChats")
    clearAllChatsFromDB().catch(() => {})
    setCurrentChatId("")
    setCurrentChatMessages([])
    setInitialMessages([])
    setInput("")
    setStatus("idle")
    setIsBuilding(false)
    setIsSending(false)
    isSendingRef.current = false
    setIsImageGenerating(false)
    setAutoGenerated(false)
    setHasSavedToGallery(false)
    setEditedAppCode("")
    setIsEditing(false)
    setLocalPreviewCode("")
    setMessagePreviews(new Map())
    setMessageImages(new Map())
    setSessionApps([])
    setCurrentAppIndex(-1)
    if (blobUrl) { URL.revokeObjectURL(blobUrl); setBlobUrl("") }
  }

  const navigateToNextApp = () => {
    if (currentAppIndex < sessionApps.length - 1) {
      const nextApp = sessionApps[currentAppIndex + 1]
      if (nextApp) {
        setLocalPreviewCode(nextApp.code)
        setCurrentAppIndex(prev => prev + 1)
        setBlobUrl("")
        setTimeout(() => {
          setBlobUrl(createBlobUrl(nextApp.code, nextApp.name))
        }, 0)
      }
    }
  }

  const navigateToPrevApp = () => {
    if (currentAppIndex > 0) {
      const prevApp = sessionApps[currentAppIndex - 1]
      if (prevApp) {
        setLocalPreviewCode(prevApp.code)
        setCurrentAppIndex(prev => prev - 1)
        setBlobUrl("")
        setTimeout(() => {
          setBlobUrl(createBlobUrl(prevApp.code, prevApp.name))
        }, 0)
      }
    }
  }

  return (
    <div className="flex h-screen bg-[#0a0a0a]">
      {shareMessage && (
        <div className="fixed top-4 left-1/2 transform -translate-x-1/2 bg-muted text-foreground px-4 py-2 rounded-lg shadow-md z-50">
          {shareMessage}
        </div>
      )}

      <SettingsPanel
        showSettings={showSettings}
        setShowSettings={setShowSettings}
        recentChats={recentChats}
        onLoadChat={loadRecentChat}
        onDeleteChat={deleteChat}
        onClearAll={clearAllChats}
      />

      {showPreview && window.innerWidth < 768 && (
        <div className="fixed inset-0 z-50 bg-[#0a0a0a]">
          <div className="flex items-center justify-between px-4 py-3">
            <span className="text-sm font-medium">{savedApps.find(app => app.code === editedAppCode)?.name || "Current Chat"}</span>
            <Button variant="ghost" size="icon" className="h-6 w-6" onClick={() => setShowPreview(false)}>
              <X className="h-4 w-4" />
            </Button>
          </div>
          <div className="h-[calc(100vh-53px)]">
            {previewImageUrl ? (
              <PreviewPanel 
                imageUrl={previewImageUrl} 
                hideBackButton={true}
                onPrev={() => {
                  const newIdx = mediaNavIndex > 0 ? mediaNavIndex - 1 : mediaAppsRef.current.length - 1
                  setMediaNavIndex(newIdx)
                  setPreviewImageUrl(mediaAppsRef.current[newIdx]?.code || null)
                }}
                onNext={() => {
                  const newIdx = mediaNavIndex < mediaAppsRef.current.length - 1 ? mediaNavIndex + 1 : 0
                  setMediaNavIndex(newIdx)
                  setPreviewImageUrl(mediaAppsRef.current[newIdx]?.code || null)
                }}
                hasPrev={mediaAppsRef.current.length > 1}
                hasNext={mediaAppsRef.current.length > 1}
                appName={savedApps.find(app => app.code === editedAppCode)?.name || "Image Preview"} 
                onConsoleMessage={handleConsoleMessage} 
                stopAutoReload={status === "ready"}
              />
            ) : blobUrl ? (
              <PreviewPanel previewUrl={blobUrl} onConsoleMessage={handleConsoleMessage} stopAutoReload={status === "ready"} />
            ) : (
              <div className="h-full flex items-center justify-center text-muted-foreground"><p className="text-sm">Preview will appear here</p></div>
            )}
          </div>
        </div>
      )}

      <div className={`flex-1 flex min-w-0 transition-all duration-300 ${showAppDrawer ? 'w-full md:w-[50%]' : 'w-full md:w-[50%]'}`}>
        <div className={`absolute top-4 left-4 z-50 ${showAppDrawer ? 'hidden md:block' : ''}`}>
          {!showSettings && !showPreview && (
            <button
              id="settings-toggle"
              onClick={() => setShowSettings(true)}
              aria-label="Open settings"
              className="p-2 text-[#666666] hover:text-[#888888] transition-colors"
            >
              <ChevronRight className="h-4 w-4" />
            </button>
          )}
        </div>

       <div className={`flex-1 flex min-h-0 ${showAppDrawer ? 'hidden md:flex' : ''}`}>
          <div className="flex-1 flex flex-col min-w-0">
            <ScrollArea className="flex-1 bg-[#0a0a0a] [&::-webkit-scrollbar]:hidden">
              <div className="px-4 py-4 space-y-4 max-w-3xl mx-auto">
                {messages.length === 0 && (
                  <div className="text-center py-16 text-[#888888]">
                    <p className="text-lg mb-3">🚀 Srishti AI</p>
                    <ul className="text-sm space-y-1">
                      <li>• Type "build a calculator" to generate a colorful app</li>
                      <li>• Ask for images: "show me a sunset"</li>
                    </ul>
                  </div>
                )}
                {messages.map((msg, idx) => {
                    const m = msg as any
                    if (m.type === 'tool-call' || m.type === 'tool-result') return null
                    const code = extractCodeFromMessage(msg)
                    const msgImageUrl = messageImages.get(idx) || (msg as any).imageUrl
                    const hasCode = code !== null
                    return (
                      <div key={msg.id} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'} gap-2`}>
                        <div className={`${msg.role === 'user' ? 'self-end' : 'self-start'} max-w-[90%]`} data-testid={msg.role === 'user' ? 'user-message' : 'assistant-message'}>
                          <ChatMessage
                            message={msg}
                            previewUrl={hasCode ? getPreviewUrl(msg) || undefined : undefined}
                            onPreviewClick={() => setShowPreview(true)}
                            onSaveToGallery={hasCode ? () => handleSaveFromChat(idx) : undefined}
                            onDownload={hasCode ? () => handleDownloadFromChat(idx) : undefined}
                            hasSavedToGallery={hasCode && isAppSavedInChat(idx)}
                            status={isLatestUserRef.current ? status : undefined}
                            isSending={isLatestUserRef.current && isSending}
                            onImageSave={msgImageUrl ? () => handleImageSaveFromChat(idx) : undefined}
                            onImageDownload={msgImageUrl ? () => handleImageDownloadFromChat(idx) : undefined}
                            onImageOpen={msgImageUrl ? () => handleImageOpenFromChat(idx) : undefined}
                            hasImageSavedToGallery={msgImageUrl && isImageSavedInChat(idx)}
                            onSuggestionClick={(suggestion) => {
                              setInput(suggestion)
                            }}
                            msgImageUrl={msgImageUrl}
                          />
                        </div>
                      </div>
                    )
                  })}
                <div ref={messagesEndRef} />
              </div>
            </ScrollArea>

            <div className="px-4 pb-6 pt-2 max-w-3xl mx-auto w-full">
              <div className="w-full">
                <ChatInput
                  isGenerating={isGenerating}
                  handleSubmit={handleSubmit} stopGeneration={stopGeneration}
                  selectedLanguage={selectedLanguage}
                  onLanguageChange={(lang) => setSelectedLanguage(lang)}
                  onNewChat={newSession}
                  onToggleGallery={() => {
                    if (showAppDrawer) {
                      setShowAppDrawer(false)
                      setPreviewImageUrl(null)
                      setShowPreview(false)
                      setBlobUrl("")
                    } else {
                      if (previewImageUrl || blobUrl) {
                        setPreviewImageUrl(null)
                        setShowPreview(false)
                        setBlobUrl("")
                      }
                      setShowAppDrawer(true)
                    }
                  }}
                />
              </div>
            </div>
          </div>
        </div>
      </div>

      <AppDrawer
        showAppDrawer={showAppDrawer} setShowAppDrawer={setShowAppDrawer}
        savedApps={savedApps} openSavedApp={openSavedApp} removeApp={removeApp}
        editApp={handleEditApp} shareApp={handleShareApp} runApp={handleRunApp}
        deleteApp={handleDeleteApp} downloadApp={handleDownloadApp}
        handleSwitchToSavedApp={handleSwitchToSavedApp}
        setLongPressedApp={setLongPressedApp}
        contextMenu={contextMenu} longPressedApp={longPressedApp}
        selectedIndex={galleryIndex} setSelectedIndex={setGalleryIndex}
        onClearAll={clearAllChats}
        onMediaClick={(app) => {
          const mediaApps = savedApps.filter(a => a.code.startsWith('data:image/') || a.code.startsWith('data:video/') || a.code.startsWith('data:audio/'))
          mediaAppsRef.current = mediaApps
          const idx = mediaApps.findIndex(a => a.id === app.id)
          setMediaNavIndex(idx >= 0 ? idx : 0)
          handleSwitchToSavedApp(app)
        }}
       />

      <div className={`transition-all duration-300 overflow-hidden ${showPreview ? "w-full sm:w-[50%]" : "w-0"}`}>
        {showPreview && (
          <>
            <div className="flex-1 h-full overflow-hidden [&::-webkit-scrollbar]:w-2 [&::-webkit-scrollbar-thumb]:bg-[#404040] [&::-webkit-scrollbar-track]:bg-transparent">
              {previewImageUrl ? (
                <PreviewPanel 
                  imageUrl={previewImageUrl} 
                  appName={sessionApps[currentAppIndex]?.name || "Image Preview"} 
                  onConsoleMessage={handleConsoleMessage} 
                  stopAutoReload={status === "ready"} 
                  onBack={() => { setShowAppDrawer(true); setShowPreview(false); setPreviewImageUrl(null) }}
                  onClose={() => { setShowPreview(false); setPreviewImageUrl(null) }}
                  onPrev={() => {
                    const newIdx = mediaNavIndex > 0 ? mediaNavIndex - 1 : mediaAppsRef.current.length - 1
                    setMediaNavIndex(newIdx)
                    setPreviewImageUrl(mediaAppsRef.current[newIdx]?.code || null)
                  }}
                  onNext={() => {
                    const newIdx = mediaNavIndex < mediaAppsRef.current.length - 1 ? mediaNavIndex + 1 : 0
                    setMediaNavIndex(newIdx)
                    setPreviewImageUrl(mediaAppsRef.current[newIdx]?.code || null)
                  }}
                  hasPrev={mediaAppsRef.current.length > 1}
                  hasNext={mediaAppsRef.current.length > 1}
                />
              ) : blobUrl ? (
                <PreviewPanel previewUrl={blobUrl} appName={sessionApps[currentAppIndex]?.name || "My App"} onConsoleMessage={handleConsoleMessage} stopAutoReload={status === "ready"} onBack={() => { setShowAppDrawer(true); setShowPreview(false) }} onClose={() => setShowPreview(false)} />
              ) : (
                <div className="h-full flex items-center justify-center text-muted-foreground"><p className="text-sm">Preview will appear here</p></div>
              )}
            </div>
            <div className="cursor-col-resize hover:bg-primary/20 transition-colors" style={{ width: '4px' }} onMouseDown={handleResizeMouseDown} />
          </>
        )}
      </div>
    </div>
  )
}
